<a href="https://colab.research.google.com/github/Myun9hyun/DataAnalysis/blob/main/Myun9hyun/ch05_02%2B03%2B04_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [24]:
arr1 = np.arange(1, 4) # 1, 2, 3
arr2 = np.arange(4, 7) # 4, 5, 6
# np.concatenate([arr1, arr2], axis = 0)
np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

In [25]:
np.concatenate([arr1, arr2, arr1, arr2])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [29]:
arr1 = arr1.reshape(3, 1)
arr2 = arr2.reshape(3, 1)

# np.concatenate([arr1, arr2])
# np.concatenate([arr1, arr2], axis=0) # 행방향
np.concatenate([arr1, arr2], axis=1) # 열방향


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [33]:
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))
np.hstack((a1, a2)) # hstack은 행의 크기가 같아야함

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [35]:
# b1 = np.ones((2, 3))
b1 = np.ones_like(a1)
b2 = np.zeros((3, 3)) 
np.vstack((b1, b2)) # vstack은 열의 크기가 같아야함

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
c1 = np.ones((3, 4))
c2 = np.zeros_like(c1)
np.dstack((c1, c2)) # 행, 열의 길이 같고, 가장 마지막(안쪽의) 차원이 1증가하면서 합쳐진다.

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [39]:
# c = np.stack([c1, c2])
c = np.stack([c1, c2], axis=0) # 행기준
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [40]:
np.stack([c1, c2], axis=-1) # 차원을 추가하면서 합쳐지는 (dstack)

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [41]:
np.stack([c1, c2], axis=1) # 열 기준

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [42]:
np.stack([c1, c2], axis=2)

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [45]:
# r_ -> hstack. 1, 2, 3/ 4, 5, 6
np.r_[np.arange(1, 4), np.arange(4, 7)]

array([1, 2, 3, 4, 5, 6])

In [47]:
np.r_[np.arange(1, 4), np.arange(4, 7), np.arange(4, 7)] # 중복 값 넣기도 가능

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [48]:
np.c_[np.arange(1, 4), np.arange(4, 7)]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
np.arange(1,4)[:, np.newaxis], np.arange(4,7)[:, np.newaxis]

(array([[1],
        [2],
        [3]]), array([[4],
        [5],
        [6]]))

In [56]:
a = np.arange(6).reshape(2, -1)
print(np.tile(a, 3)) # 모양을 지키면서 반복
print(np.repeat(a, 3)) # flattern 시킨 다음에 , 각 원소들을 그 위치에 반복

[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [57]:
arr = np.arange(7) # 1, 2, 3, 4, 5, 6
arr

array([0, 1, 2, 3, 4, 5, 6])

In [64]:
np.array_split(arr, 3) # array_split은 그냥 되는대로 등분

[array([0, 1]), array([2, 3]), array([4, 5])]

In [65]:
arr = np.arange(6) # split -> 엄격하게 약수로 맞춰서 입력해야 쪼개줌
np.split(arr, 3)

[array([0, 1]), array([2, 3]), array([4, 5])]

In [67]:
arr = np.arange(1, 19).reshape(-1, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [69]:
np.array_split(arr, 3) # 행 방향으로 자름
np.array_split(arr, 3, axis = 0) # 행 방향으로 자름


[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]), array([[13, 14, 15],
        [16, 17, 18]])]

In [71]:
np.array_split(arr, 3, axis = 1) # 열 방향으로 자름

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [94]:
# 브로드캐스팅 : 크기가 작은 배열을 자동으로 반복확장하여 크기가 큰 배열에 맞추는 방법
x = np.arange(5)
x + 1

array([1, 2, 3, 4, 5])

In [77]:
x + np.ones_like(x) * 1

array([1, 2, 3, 4, 5])

In [79]:
x + 10

array([10, 11, 12, 13, 14])

In [81]:
np.ones_like(x) * 10

array([10, 10, 10, 10, 10])

In [95]:
# x + np.ones_like(x) * 10
x + np.full_like(x, 10)

array([10, 11, 12, 13, 14])

In [116]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [99]:
y = np.arange(5).reshape(-1, 1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [101]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [102]:
x = np.arange(1, 5) # 1, 2, 3, 4

In [104]:
np.sum(x), x.sum()

(10, 10)

In [106]:
x.min(), x.max()

(1, 4)

In [108]:
x.argmin(), x.argmax()

(0, 3)

In [109]:
x.mean(), np.mean(x)

(2.5, 2.5)

In [112]:
np.median(x)

2.5

In [114]:
np.any(x > 4), np.any(x > 2)

(False, True)

In [118]:
np.all(x > 4), np.any(x > 2) , np.any(x >=  0)

(False, True, True)

In [120]:
x = np.array(((1,1), (2, 2)))
x

array([[1, 1],
       [2, 2]])

In [122]:
x.sum()

6

In [125]:
x.sum(axis=0) # 행 내부에 있는 열들간의 연산, 행의 대푯값(axis = 0)

array([3, 3])

In [126]:
x.sum(axis=1) # 열 내부에 있는 열들간의 연산, 열의 대푯값(axis = 1)

array([2, 4])

In [134]:
a = np.random.randint(1, 20, 12).reshape(3, -1)
a

array([[ 9, 12, 13,  2],
       [11, 19, 12, 13],
       [ 7,  4, 19,  6]])

In [143]:
np.sort(a) # 행을 그대로, 열들 간의 정리 axis = 0
np.sort(a, axis = 1) # 행을 그대로, 열들간의 정리 axis = 1
np.sort(a, axis = - 1) # 행을 그대로, 열들간의 정리 axis = -1


array([[ 2,  9, 12, 13],
       [11, 12, 13, 19],
       [ 4,  6,  7, 19]])

In [139]:
np.sort(a, axis = 0) # 행을 그대로, 열들간의 정리 axis = 0

array([[ 7,  4, 12,  2],
       [ 9, 12, 13,  6],
       [11, 19, 19, 13]])

In [140]:
a.sort(axis=1) # in-place

In [144]:
a

array([[ 2,  9, 12, 13],
       [11, 12, 13, 19],
       [ 4,  6,  7, 19]])

In [146]:
np.argsort(a)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [151]:
np.argsort(a, axis=0)

array([[0, 2, 2, 0],
       [2, 0, 0, 1],
       [1, 1, 1, 2]])

In [154]:
x = np.random.randint(0, 100, 12).reshape(3, -1)
x

array([[48, 47,  1, 21],
       [73, 49, 18,  4],
       [19, 93, 56,  6]])

In [155]:
x[:, np.argsort(x[1])];l

array([[21,  1, 47, 48],
       [ 4, 18, 49, 73],
       [ 6, 56, 93, 19]])

In [157]:
x = np.random.randint(-30, 30, 30)
x

array([ 24, -14, -10, -15, -12,  26,  22,  -3, -28,  -4,   1, -29, -10,
         7,   8, -22, -26,  23,   6,  -7, -15,  24,   4,  24,  25,  16,
       -30,  13,  21, -20])

In [158]:
len(x)

30

In [160]:
np.mean(x), x.mean()

(-0.03333333333333333, -0.03333333333333333)

In [162]:
np.var(x) # 평균과 원소들 사이의 값을 제곱

340.76555555555547

In [163]:
np.std(x)

18.45983628192719

In [164]:
np.max(x), np.min(x)

(26, -30)

In [165]:
np.max(x), np.min(x)

(26, -30)

In [167]:
np.median(x) # 짝수개라서 중앙값이 없을 경우엔, 중앙 두개를 더한 후 절반으로 나눔(두 값의 평균)

-1.0

In [170]:
np.quantile(x, 0), np.percentile(x, 0) # 최솟값

(-30, -30.0)

In [173]:
# 사분위 수 => 1을 최대로 봤을 때의 비율수. 1/4, 2/4, 3/4...
# 백분위 수는 100을 최대로 봤을 때의 값을 입력
np.quantile(x, 0.25), np.percentile(x, 25) # 1사분위 수, 25백분위 수

(-14.75, -14.75)

In [175]:
np.quantile(x, 0.5), np.percentile(x, 50) # 2사분위수, 50백분위 수 , 중앙값

(-1.0, -1.0)

In [176]:
np.quantile(x, 3/4) , np.percentile(x, 75) # 3사분위수, 75백분위 수

(19.75, 19.75)

In [177]:
np.quantile(x, 4/4), np.percentile(x, 100) # 최댓값

(26.0, 26.0)

In [178]:
# np.random.seed(0) 이후 나오는 랜덤값들이 순서가 일치
np.random.seed(10) # 이후 나오는 랜덤값들이 순서가 일치 

In [180]:
np.random.rand(5)

array([0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [182]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
np.random.shuffle(x)

In [186]:
x

array([1, 6, 2, 5, 7, 8, 9, 0, 3, 4])

In [187]:
np.random.choice(x, 5, replace=False) # 배열 안의 있는 값 중에 5개를 추출(비복원)

array([1, 0, 8, 2, 5])

In [189]:
np.random.choice(5, 5, replace=False)

array([0, 4, 2, 1, 3])

In [190]:
np.random.choice(np.arange(1, 46), 6, replace=False) # 비복원추출

array([42,  4, 27, 41,  3,  7])

In [193]:
np.random.choice(np.arange(1,7), 6, replace= True)

array([1, 6, 1, 6, 6, 3])

In [240]:
np.random.choice(np.arange(1, 7), 6, p=[0.0001, 0.1, 0.4, 0.4, 0, 0.0999])

array([6, 3, 4, 3, 2, 6])

In [215]:
np.random.randn(10) # 0 평균, 표준편차 -1. -2. +2 => 99.9%  0에 가까울 수록 값들이 더 많이 등장

array([ 0.67460893,  1.03721415, -0.90275152, -1.71127559,  0.83252589,
        0.82925179, -1.51922496, -1.39566483,  0.4696549 ,  0.62068802])

In [216]:
np.random.randn(3, 5)

array([[ 0.50592734, -0.66529829,  0.71320576,  0.16040769, -0.86114822],
       [-0.18135502,  0.3092563 ,  0.5835395 , -1.70248659, -0.6405794 ],
       [-0.40639349, -1.72494118, -1.59832368,  1.26149721, -0.5807007 ]])

In [217]:
np.random.randint(10) # 최소 0, low

7

In [218]:
np.random.randint(1, 10) # 최소 low, 최대 high

1

In [219]:
np.random.randint(1, 10, 100) # 최소 low, 최대 high, size

array([3, 3, 1, 6, 9, 1, 6, 4, 7, 8, 9, 1, 7, 1, 2, 1, 2, 5, 1, 2, 8, 4,
       1, 9, 2, 6, 5, 6, 5, 4, 5, 5, 2, 2, 3, 2, 2, 3, 3, 3, 6, 9, 2, 8,
       2, 8, 2, 9, 1, 7, 8, 6, 2, 3, 7, 2, 6, 9, 1, 4, 7, 4, 1, 3, 9, 9,
       1, 8, 8, 5, 7, 4, 5, 6, 4, 6, 3, 4, 3, 3, 6, 9, 5, 2, 7, 8, 2, 8,
       2, 3, 3, 8, 5, 7, 8, 4, 3, 4, 3, 6])

In [258]:
# ## 가격이 1만원 주식
# price = 10000
# ## 일간 수익률 => 기댓값(평균) 0, 표준편차 1% = 0.01 (표준정규분포)
# days = 250
# daily_earning_rate = np.random.randn(days) / 100
# ## 250일 동안의 주가를 무작위로 생성
# ## 주가 -> 전일 가격 * (1 + 당일 수익률)
# price_arr = np.empty(days)
# for i, v in enumerate(daily_earning_rate):
#     price *= (1 + v)
#     print(price)
#     price_arr[i] = price
#     print(price_arr[i])
#     print(price_arr)
# price_arr
# 값이 너무 많아서 전부 주석처리함..!

In [245]:
x = np.random.randint(1, 10, 100)
x

array([7, 7, 5, 4, 6, 5, 2, 6, 4, 4, 2, 1, 6, 3, 8, 4, 8, 1, 5, 4, 6, 1,
       2, 8, 1, 6, 1, 2, 9, 2, 8, 5, 4, 4, 1, 5, 7, 7, 7, 9, 4, 6, 8, 1,
       9, 2, 3, 4, 6, 2, 7, 2, 1, 3, 1, 7, 8, 6, 7, 1, 5, 8, 1, 1, 8, 6,
       1, 2, 1, 8, 8, 3, 8, 9, 6, 9, 3, 5, 1, 1, 2, 7, 6, 3, 1, 2, 8, 4,
       2, 2, 5, 2, 8, 4, 3, 9, 6, 3, 5, 4])

In [246]:
np.unique(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [247]:
np.unique(x, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([17, 14,  8, 12,  9, 12,  9, 13,  6]))

In [248]:
np.unique(x, return_counts=True, return_index=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([11,  6, 13,  3,  2,  4,  0, 14, 28]),
 array([17, 14,  8, 12,  9, 12,  9, 13,  6]))

In [249]:
key, value = np.unique(x, return_counts=True)
print(key)
print(value)

[1 2 3 4 5 6 7 8 9]
[17 14  8 12  9 12  9 13  6]


In [259]:
# 2개의 시퀀스를, 인덱스로 묶어줌 zip
list(zip(key, value))

[(1, 17), (2, 14), (3, 8), (4, 12), (5, 9), (6, 12), (7, 9), (8, 13), (9, 6)]

In [260]:
dict(list(zip(key, value)))

{1: 17, 2: 14, 3: 8, 4: 12, 5: 9, 6: 12, 7: 9, 8: 13, 9: 6}

In [261]:
dict(zip(key, value))

{1: 17, 2: 14, 3: 8, 4: 12, 5: 9, 6: 12, 7: 9, 8: 13, 9: 6}

In [262]:
dict(zip(*np.unique(x, return_counts=True)))

{11: 1, 12: 1, 14: 1, 20: 1, 21: 1, 22: 1, 25: 1, 26: 1, 29: 2}

In [257]:
x = np.random.randint(1, 30, 10)
x

array([20, 12, 29, 25, 22, 11, 14, 26, 29, 21])

In [263]:
dict(zip(*np.unique(x, return_counts=True)))

{11: 1, 12: 1, 14: 1, 20: 1, 21: 1, 22: 1, 25: 1, 26: 1, 29: 2}

In [264]:
np.bincount(x, minlength=30)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 2])

In [265]:
np.arange(30), np.bincount(x, minlength=30)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 1, 0, 0, 2]))

In [266]:
zip(np.bincount(x, minlength=30))