<a href="https://colab.research.google.com/github/Myun9hyun/DataAnalysis/blob/main/Myun9hyun/ch05_01%2B02_%EB%B3%B5%EC%8A%B5_Myun9hyun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
!pip install numpy
import numpy as np
import time

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [18]:
%time
np.array([1, 2, 3, 4, 5])

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 4.05 µs


array([1, 2, 3, 4, 5])

In [8]:
np.array((1, 2, 3))

array([1, 2, 3])

In [11]:
np.array(range(1, 4))

array([1, 2, 3])

In [14]:
np.array([c for c in "1234"])

array(['1', '2', '3', '4'], dtype='<U1')

In [16]:
np.array([int(c) for c in "123"])

array([1, 2, 3])

In [21]:
arr = np.array([1, 2, 3])

In [22]:
type(arr) # n-dimentional array

numpy.ndarray

## 벡터화 연산

In [41]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
a + [10] # 리스트 내부에 요소 10을 넣은것이지 리스트 전체를 10 더한것이 아님

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [33]:
a * 2 # 리스트 요소 *2 가 아니라 리스트의 길이를 2배로 늘린 것임.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
[v * 2 for v in a] # 리스트 컴프리헨션을 쓰면 가능. 
# v 가 a의 원소를 복사해서 사용하는 것이기 때문!

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [47]:
[v for v in a]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [79]:
arr = np.arange(10) # np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr + 2 # 배열(np.ndarray)에서 산술 연산자는 각각의 원소들에 대해서 계산 진행

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
arr + np.ones_like(arr) * 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
np.ones_like(arr) * 2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [68]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [72]:
(((arr * 5) // 2) - 1) % 7

array([6, 1, 4, 6, 2, 4, 0, 2, 5, 0])

In [74]:
arr == 5

array([False, False, False, False, False,  True, False, False, False,
       False])

In [75]:
arr[arr == 5]

array([5])

In [81]:
arr[arr > 5]

array([6, 7, 8, 9])

In [84]:
np.where(arr > 5)

(array([6, 7, 8, 9]),)

In [86]:
arr2 = np.arange(6, 25, 2)
arr2

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [89]:
np.where(arr2 % 3 == 0)

(array([0, 3, 6, 9]),)

In [91]:
arr2[np.where(arr2 % 3 == 0)] #<- 정수 인덱싱 arr2[arrw % 3 == 0] <- 불리언 인덱싱

array([ 6, 12, 18, 24])

In [94]:
arr2[[0] * 5]

array([6, 6, 6, 6, 6])

In [104]:
(arr > 5) & (arr % 2 == 0) # 조건에는 ()가 필수

array([False, False, False, False, False, False,  True, False,  True,
       False])

* https://www.facebook.com/groups/codingeverybody/posts/873281936045677/

```
! - bang(뱅)Exclamation Point(엑스클러메이션 포인트)
# - Crosshatch(크로스해치), Sharp(샵), Pound Sign(파운드사인)
$ - Dollar Sign (달러사인)
% - Percent Sign(퍼센트사인)
@ - At Sign (앳 사인), Commercial At(커머셜 앳)
& - Ampersand(앰퍼샌드) snowman
' - single quote(싱글쿼트) Apostrophe(어퍼스트로피), single quotation mark
" - double quote(더블쿼트)Quotation Mark(쿼테이션마크) , Double Quotation Mark
* - Asterisk(애스터리스크)
. - Period(피리어드), Full Stop(풀스탑)
/ - Slash (슬래시), Virgule(버귤)
\ - Back Slash(백슬래시)
: - Colon (콜론)
; - Semicolon(세미콜론)
^ - Circumflex(서컴플렉스), Caret(캐럿)
`(<<~이랑 같이 있는 넘) - Back Quote(백쿼트)Grave(그레이브)
{} - Brace(브레이스) (중괄호) curly braces/curly brackets
[] - Bracket(브래킷) (대괄호) brackets/square brackets
() - Parenthesis(퍼렌씨시스) (괄호)
| - Vertical Bar(버티컬바)
~ - Tilde (틸드)
= - Equal sign(이퀄사인)
+ - Plus Sign(플러스사인)
- - Minus Sign(마이너스사인)Hyphen(하이픈),Dash(대시)
_ - Underscore(언더스코어),Underline(언더라인)
< - Less Than Sign(레스댄 사인), Left Angle Bracket(레프트 앵글브래킷)
> - Greater Than Sign(그레이터댄 사인), Right Angle Bracket(라이트 앵글 브래킷)
? - Question Mark(물음표)
```

In [106]:
# ndarray
np.array([1, 2, 3, 4]), ([1, 2, 3, 4])

(array([1, 2, 3, 4]), [1, 2, 3, 4])

In [115]:
np.array([[1, 2, 3, 4], [1, 2, 3]]) # 모양이 다르기 때문에 깨짐(행렬 성립이 x)

<ipython-input-115-038fd20fe040>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, 2, 3, 4], [1, 2, 3]]) # 모양이 다르기 때문에 깨짐(행렬 성립이 x)


array([list([1, 2, 3, 4]), list([1, 2, 3])], dtype=object)

In [116]:
a1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [118]:
a2 = np.array([[1, 2, 3], [1, 2, 3, 4]])
a2 # 마찬가지로 행렬이 서로 크기가 달라 성립x(차원을 서로 맞춰줘야함)

<ipython-input-118-f9d6bdf5d4a1>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = np.array([[1, 2, 3], [1, 2, 3, 4]])


array([list([1, 2, 3]), list([1, 2, 3, 4])], dtype=object)

In [120]:
a1.ndim, a1.shape

(2, (2, 4))

In [121]:
a2.ndim, a2.shape

(1, (2,))

In [128]:
m = np.array([[1, 2], [3,4]])
m2 = np.array((range(2,4), range(5,7)))
print(m)
print(m2)

[[1 2]
 [3 4]]
[[2 3]
 [5 6]]


In [132]:
t = np.array([
    [
        [1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 11, 2, 3],
    ],
    [
    [2, 3, 4, 5],
    [14, 4, 5, 6],
    [312, 4, 5, 6]
]
    
])
t

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  11,   2,   3]],

       [[  2,   3,   4,   5],
        [ 14,   4,   5,   6],
        [312,   4,   5,   6]]])

In [135]:
t.ndim, t.shape

(3, (2, 3, 4))

In [136]:
a = np.arange(10).reshape(2, 4) # 10이 나와야 하는데 8 나왔음.
# shape에 들어가는 매개번수는 모두 곱했을 때 전체원소의 크기가 나와야함.

ValueError: ignored

In [138]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [142]:
b = a
b[0,1] = 9

In [143]:
print(a)
print(b)

[[0 9 2 3 4]
 [5 6 7 8 9]]
[[0 9 2 3 4]
 [5 6 7 8 9]]


In [148]:
c = a.copy()
c[1,1] = -137
print(a)
print(c)

[[0 9 2 3 4]
 [5 6 7 8 9]]
[[   0    9    2    3    4]
 [   5 -137    7    8    9]]


In [150]:
a = np.arange(1, 100, 25)
a

array([ 1, 26, 51, 76])

In [154]:
a[2], a[-1], a[len(a)-1], a[a.shape[0]-1]

(51, 76, 76, 76)

In [245]:
# ,(콤마) [][]
m = np.arange(6).reshape((2, 3)) # reshape(행,열)
m

array([[0, 1, 2],
       [3, 4, 5]])

In [170]:
m[0, 0], m[0, 1]

(0, 1)

In [246]:
m.ndim, m.shape #m.shape(행의 길이, 열의 길이)

(2, (2, 3))

In [162]:
m[-2, 0], m[-2, -1]

(0, 2)

In [247]:
m[m.shape[0]-2, 0], m[m.shape[0]-2, m.shape[1]-1]
# m.shape(0) : 행, m.shape(1) : 열

(0, 2)

In [167]:
d1, d2 = m.shape # d1 : 행차원의 길이, d2 : 열차원의 길이

In [168]:
m[d1-2, 0], m[d1-2, d2-1]

(0, 2)

In [189]:
a[1:2]
# 1차원의 배열의 슬라이싱 = 리스트의 슬라이싱과 같다

array([26])

In [191]:
a2 = np.arange(0, 100, 10)
a2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [199]:
a2[1:10:2], a2[10::-2], a2[::-1], a2[:]

(array([10, 30, 50, 70, 90]),
 array([90, 70, 50, 30, 10]),
 array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [201]:
m

array([[0, 1, 2],
       [3, 4, 5]])

In [204]:
m[0,:], m[0]

(array([0, 1, 2]), array([0, 1, 2]))

In [208]:
m[:,0]

array([0, 3])

In [210]:
print(m[:,0:1])

[[0]
 [3]]


## 배열의 자료형

In [248]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [249]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [251]:
x = np.array([1, 2.0, "3"])
x.dtype

dtype('<U32')

In [252]:
x = np.array([1, 2, 3], dtype='i')
x2 = np.array([1, 2, 3], dtype=int)
print(x, x.dtype)
print(x2, x2.dtype)

[1 2 3] int32
[1 2 3] int64


In [ ]:
x = np.array([1, 2, 3], dtype='f')
x2 = np.array([1, 2, 3], dtype=float)
print(x, x.dtype)
print(x2, x2.dtype)

In [254]:
x = np.array([1, 2, 3.5], dtype='i') # 3.5의 소수점 아래는 버림(int형이기 때문)

print(x, x.dtype)


[1 2 3] int32


In [258]:
a = np.zeros(5)
b = np.array([0, 1, 0, 1, 0]) # -> 0 / 0 -> nan, not a number -> na
a / b, b / a # 1/ 0 -> inf, infinite

<ipython-input-258-39368e75d218>:3: RuntimeWarning: invalid value encountered in true_divide
  a / b, b / a
<ipython-input-258-39368e75d218>:3: RuntimeWarning: divide by zero encountered in true_divide
  a / b, b / a


(array([nan,  0., nan,  0., nan]), array([nan, inf, nan, inf, nan]))

In [259]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [261]:
np.ones(5) # 배열의 덧셈, 뺄셈등을 할때 받아주는 것이 필요할때 사용

array([1., 1., 1., 1., 1.])

In [263]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [265]:
np.zeros_like(a) # a와 모양이 같은 배열인데 0으로 채운 배열

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [266]:
np.ones_like(a)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [270]:
np.empty((2, 5))

array([[2.22716572e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [5.19909577e+170, 7.61458196e+169, 7.43098324e-091,
        5.92655557e-062, 2.20894729e+161]])

In [272]:
np.linspace(10, 100, 5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [275]:
np.logspace(1, 100, 5)

array([1.00000000e+001, 5.62341325e+025, 3.16227766e+050, 1.77827941e+075,
       1.00000000e+100])

In [278]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [281]:
A.ndim, A.shape

(2, (2, 3))

In [289]:
A[A.shape[0]-2, -1], A[A.shape[0]-1, -1]

(3, 6)

In [290]:
A2 = A.T # 행과 열의 위치를 바꾸는 것 -> (1,2) -> (2,1)
A2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [292]:
A2.ndim, A2.shape

(2, (3, 2))

In [298]:
A, A.flatten(), A.ravel()

(array([[1, 2, 3],
        [4, 5, 6]]), array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 4, 5, 6]))

In [300]:
t = np.arange(30).reshape(3, 5, 2)
t

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [301]:
t.flatten(), t.ravel()

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))

In [357]:
x = np.arange(5)
print(x, x.ndim, x.shape)
x2 = x[:, np.newaxis]
print(x2, x2.ndim, x2.shape)
x3 = x[np.newaxis,:]
print(x3, x3.ndim, x3.shape)

[0 1 2 3 4] 1 (5,)
[[0]
 [1]
 [2]
 [3]
 [4]] 2 (5, 1)
[[0 1 2 3 4]] 2 (1, 5)
