<a href="https://colab.research.google.com/github/Myun9hyun/DataAnalysis/blob/main/Myun9hyun/ch05_04_%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84%2B%EB%82%9C%EC%88%98%EB%B0%9C%EC%83%9D%EA%B3%BC%2B%EC%B9%B4%EC%9A%B4%ED%8C%85_Myun9hyun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기술 통계

## 기술 통계(descriptive statistics)
> 데이터 집합에 대해 통계를 계산
* 데이터의 개수(count)
* 평균(mean, average)
* 분산(variance)
* 표준 편차(standard deviation)
* 최댓값(maximum)
* 최솟값(minimum)
* 중앙값(median)
* 사분위수(quartile)

In [ ]:
import numpy as np

## 데이터의 개수

In [ ]:
x = np.array([
    18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 
    2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13
])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 표본 평균
* 우리가 일반적으로 아는 평균
* 통계용어로는 표본 평균(sample average, sample mean)
<br>
$
\bar{x} = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{x_i}
$
(𝑁은 데이터의 개수)

In [ ]:
np.mean(x), x.mean()

(4.8076923076923075, 4.8076923076923075)

## 표본 분산
* 표본 분산(sample variance) : 데이터와 표본 평균간의 거리의 제곱의 평균
* 표본 분산이 작으면 데이터가 모여있는 것이고 크면 흩어져 있는 것
<br>
$
s^2 = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{(x_i-\bar{x})^2}
$

In [ ]:
np.var(x)

115.23224852071006

## 표본 표준편차
* 표본 표준편차(sample standard variance) : 표본 분산의 양의 제곱근 값 
<br>
$
s = \sqrt{s^2}
$

In [ ]:
np.std(x)

10.734628476137871

## 최댓값과 최솟값

In [ ]:
# 최댓값 (maximum) / 최솟값 (minimum)
np.max(x), np.min(x)

(23, -24)

## 중앙값
* 중앙값(median) : 데이터를 크기대로 정렬하였을 때 가장 가운데에 있는 수
* 만약 데이터의 수가 짝수이면 가장 가운데에 있는 두 수의 평균을 사용


In [ ]:
np.median(x)

5.0

## 사분위수
* 사분위수(quartile) : 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수
* 각각 1사분위수, 2사분위수, 3사분위수라고 함
* 1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%
* 따라서 2사분위수는 중앙값과 같음
* 때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 함
* 1사분위수는 25% 백분위수와 같음


In [ ]:
np.percentile(x, 0) # 최솟값 

-24.0

In [ ]:
np.percentile(x, 25) # 25% 백분위수, 1사분위수

0.0

In [ ]:
np.percentile(x, 50) # 50% 백분위수, 2사분위수, 중앙값

5.0

In [ ]:
np.percentile(x, 75) # 75% 백분위수, 3사분위수


10.0

In [ ]:
np.percentile(x, 100) # 100% 백분위수, 4사분위수


23.0

# 난수 발생과 카운팅

## 시드 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아님
* 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성. 이런 시작 숫자를 시드(seed)라고 함
* 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 됨. 따라서 시드값은 한 번만 정해주면 됨.
* 시드는 보통 현재 시각 등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음 * 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있음
* 고정된 결과를 얻기 위해서 실습엔 시드를 설정

In [19]:
np.random.seed(0) # 시드값 고정

### `rand` : 0과 1 사이의 난수를 발생

In [26]:
np.random.rand(5) # n개의 길이를 가지는 배열에 각각 0 ~ 1 사이의 난수를 채워줌

array([0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ])

In [27]:
np.random.rand(10)

array([0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ,
       0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672])

## 데이터의 순서 변경

### `shuffle`
* 데이터의 순서를 변경
* 자체 변환(in-place) 함수 (원본에 영향)

In [28]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.random.shuffle(x)
x

array([6, 2, 1, 0, 7, 5, 3, 9, 4, 8])

## 데이터 샘플링
* 표본선택 혹은 샘플링(sampling) : 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것

### `choice` : 샘플링에 사용
```
numpy.random.choice(a, size=None, replace=True, p=None)
```
* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능 (복원/비복원 추출)
* p : 배열. 각 데이터가 선택될 수 있는 확률

In [36]:
np.random.choice(5, 5, replace=True) # replace=True : 복원추출(뽑혀도 다시 뽑힐 수 있음) 

array([0, 1, 0, 2, 2])

In [ ]:
np.random.choice(5, 5, replace=False)# replace = False : 비복원추출(뽑히면 다시 안 뽑힘)

In [37]:
np.random.choice(5, 10) # 복원, 5개중에 10개를 선택 

array([3, 2, 3, 2, 1, 2, 3, 3, 3, 2])

In [38]:
# [0, 1, 2, 3, 4]
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 확률 0 으로 지정한 배열 내의 1과 4는 절대 출력되지 않음.

array([3, 3, 3, 3, 3, 0, 2, 0, 3, 3])

In [60]:
np.random.choice([1, 5, 10, 20, 100],10, p=[0.7, 0.2, 0.05, 0.03, 0.02])

array([  1,   1,   1,   1,   1,   1,   1, 100,   1,   1])

## 난수 생성
* `rand` : 0부터 1 사이의 균일 분포
* `randn` : 표준 정규 분포
* `randint` : 균일 분포의 정수 난수

### `rand` : 0부터 1 사이에서 균일한 확률 분포로 실수 난수를 생성
* 숫자 인수는 생성할 난수의 크기
* 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [44]:
np.random.rand(10)

array([0.26034093, 0.53702252, 0.44792617, 0.09956909, 0.35231166,
       0.46924917, 0.84114013, 0.90464774, 0.03755938, 0.50831545])

In [46]:
np.random.rand(3, 5)

array([[0.16684751, 0.77905102, 0.8649333 , 0.41139672, 0.13997259],
       [0.03322239, 0.98257496, 0.37329075, 0.42007537, 0.05058812],
       [0.36549611, 0.01662797, 0.23074234, 0.7649117 , 0.94412352]])

### `randn` : 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

In [48]:
np.random.randn(10)

array([-0.77979698,  1.21390595, -2.12251201, -0.13776681, -0.41732262,
       -0.40653653,  1.06095115, -0.1035225 ,  0.14181683,  0.58181974])

In [61]:
np.random.randn(3, 5)

array([[ 1.13995339, -0.61716593, -1.77555859, -1.11820547, -1.60638701],
       [-0.81467608,  0.3212809 , -0.12393044,  0.02212126, -0.32128651],
       [ 0.69261805, -0.35352352,  0.81228996, -1.14178779, -0.28754879]])

### `randint`
```
numpy.random.randint(low, high=None, size=None)
```
만약 `high`를 입력하지 않으면 0과 `low`사이의 숫자, `high`를 입력하면 `low`와 `high`는 사이의 숫자를 출력. `size`는 난수의 숫자

In [63]:
np.random.randint(10, size = 10)

array([6, 3, 2, 9, 8, 1, 4, 0, 8, 3])

In [68]:
np.random.randint(10, 20, size = 10)

array([14, 17, 13, 10, 15, 19, 13, 17, 15, 15])

In [69]:
np.random.randint(10, 20, size = (3, 5))

array([[18, 10, 18, 13, 16],
       [19, 13, 12, 17, 10],
       [13, 10, 13, 16, 11]])

## 💡 연습문제 7
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 작성하라
2. 주사위를 100번 던져서 나오는 숫자의 평균
3. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [70]:
# 1.
np.random.choice([0,1], size=10, replace=True)

array([0, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [87]:
# 2.
# np.random.randint(1,7,100).mean()
np.random.choice(range(1,7), 100).mean()

3.53

In [94]:
# 3.
a = np.random.randn(250) / 100 # 일간 수익률의 표준정규분포를 따르는 (0,1%) 수익률 분포

In [95]:
init = 10000
stock = np.empty(250)
for i, v in enumerate(a):
    init *= (1 + v)
    stock[i] = init
stock

array([10120.18770076,  9995.72495411,  9947.0759876 ,  9843.19152032,
        9887.74298545,  9805.24134115,  9868.68362873,  9903.74272398,
        9936.673081  ,  9794.01781009,  9718.58668748,  9666.36350557,
        9596.24012186,  9560.99266811,  9776.84871891,  9848.03675452,
        9740.63365195,  9549.50598527,  9568.33029105,  9600.56020376,
        9536.8265018 ,  9632.68809601,  9658.05702649,  9644.20336977,
        9735.67847321,  9708.77434172,  9761.17121776,  9519.22409662,
        9696.45823501,  9743.24177776,  9646.06829339,  9671.89739169,
        9655.72930847,  9727.53313349,  9590.23586016,  9505.4909897 ,
        9461.32718309,  9515.5083051 ,  9538.11274617,  9593.7423767 ,
        9428.21802452,  9558.06771136,  9671.74672455,  9669.88055341,
        9861.66406692,  9781.23048914,  9902.72858305, 10059.11729229,
       10053.77414637, 10030.09027866, 10136.15777009,  9983.31754257,
        9992.81002269,  9988.77907801,  9852.72995196,  9826.04950145,
      

## 정수 데이터 카운팅
* 만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석

### `unique`
* unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
* return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력


In [96]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [99]:
a = np.array(['a', 'b', 'c','b', 'a'])
index, count = np.unique(a, return_counts=True)

In [100]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [102]:
count

array([2, 2, 1])

In [104]:
dict(zip(*np.unique(a, return_counts=True)))

{'a': 2, 'b': 2, 'c': 1}

### `bincount`
* `unique` 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않음
* 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 `bincount` 함수에 `minlength` 인수를 설정하여 쓰는 것이 더 편리
* `bincount` 함수는 0 부터 `minlength` - 1 까지의 숫자에 대해 각각 카운트
* 데이터가 없을 경우에는 카운트 값이 0이 됨

In [106]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0])