<a href="https://colab.research.google.com/github/mastgm0817/DataAnalysis/blob/main/mastgm0817/ch05_01%2B02_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install numpy
import numpy as np # 규칙, 규약

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
np.array((1, 2, 3))

array([1, 2, 3])

In [ ]:
np.array(range(1, 4))

array([1, 2, 3])

In [ ]:
np.array([int(c) for c in "123"])

array([1, 2, 3])

In [ ]:
arr = np.array([1, 2, 3])

In [ ]:
type(arr) # n-dimentinal array

numpy.ndarray

## 벡터화 연산

In [2]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
a + [10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
a * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
[v for v in a]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
[v+2 for v in a]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [7]:
[v*2 for v in a]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
import numpy as np
arr = np.arange(10) # np.array(range(10))과 같음
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr + np.ones_like(arr) * 2 # 연산 우선순위를 고려할것. 먼저 1로 배열을 만들고 곱한다음 덧셈

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
(((arr * 5) // 2) -1) % 7

array([6, 1, 4, 6, 2, 4, 0, 2, 5, 0])

In [13]:
arr == 5

array([False, False, False, False, False,  True, False, False, False,
       False])

In [14]:
arr[arr == 5]

array([5])

In [15]:
arr[arr>5]

array([6, 7, 8, 9])

In [16]:
np.where(arr>5)

(array([6, 7, 8, 9]),)

In [18]:
arr2 = np.arange(6,25,2)
arr2

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [19]:
np.where(arr2 % 3 ==0)

(array([0, 3, 6, 9]),)

In [20]:
arr2[np.where(arr2 % 3 == 0)] # arr2[arr2 % 3 == 0]

array([ 6, 12, 18, 24])

In [22]:
arr2[[0] * 5]

array([6, 6, 6, 6, 6])

In [26]:
arr[(arr>5) | (arr % 2 == 0)]

array([0, 2, 4, 6, 7, 8, 9])

In [29]:
a= np.arange(1,100,25)
a

array([ 1, 26, 51, 76])

In [31]:
a[3], a[-1], a[a.shape[0]-1]
a.shape[0]

4

In [33]:
m = np.arange(6).reshape((2,3))
m

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
m[0,0], m[0,1]

(0, 1)

In [35]:
m.ndim, m.shape

(2, (2, 3))

In [36]:
m[-2, 0], m[-2,-1]

(0, 2)

In [37]:
m[m.shape[0]-2,0], m[m.shape[0]-2, m.shape[1]-1]

(0, 2)

In [38]:
m.shape[0]

2

In [40]:
d1, d2 = m.shape
row_length, column_length = m.shape


(2, 3)

In [41]:
m[d1-2,0], m[d1-2, d2-1]

(0, 2)

In [43]:
a[1:2]

array([26])

In [44]:
a2 = np.arange(0,100,10)
a2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
a2[1:10:2], a2[10::-1], a2[::-1], a2[:]

(array([10, 30, 50, 70, 90]),
 array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0]),
 array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

# 배열의 자료형

In [48]:
x = np.array([1,2,3])
x.dtype

dtype('int64')

In [49]:
x = np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [51]:
x = np.array([1,2.0,3])
x.dtype

dtype('float64')

In [53]:
x = np.array([1,2.0,'a'])
x.dtype

dtype('<U32')

In [55]:
x = np.array([1,2,3], dtype="i") # i = integer 32
x2 = np.array([1,2,3], dtype="int") # i = integer 64
print(x,x.dtype)
print(x2,x2.dtype)

[1 2 3] int32
[1 2 3] int64


In [56]:
x = np.array([1,2,3], dtype="f") # i = integer 32
x2 = np.array([1,2,3], dtype="float") # i = integer 64
print(x,x.dtype)
print(x2,x2.dtype)

[1. 2. 3.] float32
[1. 2. 3.] float64


In [57]:
x = np.array([1,2,3.5], dtype='i')
print(x, x.dtype)

[1 2 3] int32


In [58]:
x = np.array([1,2,'안녕'], dtype='i')
print(x, x.dtype)

ValueError: ignored

In [59]:
a = np.zeros(5)
b = np.array([0,1,0,1,0])
a / b # nan(not a number)

<ipython-input-59-b81cb29ea14a>:3: RuntimeWarning: invalid value encountered in true_divide
  a / b


array([nan,  0., nan,  0., nan])

In [61]:
np.zeros_like(a)

array([0., 0., 0., 0., 0.])

In [63]:
np.ones_like(a)

array([1., 1., 1., 1., 1.])

In [64]:
np.empty((2,5))

array([[2.56606155e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [5.16182408e-066, 2.14330615e+184, 5.45502645e-090,
        1.69095298e-052, 6.92840098e-310]])

In [65]:
np.linspace(10,100,5) # 10부터 100구간을 5등분 시키겠다.

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [66]:
np.logspace(0.1, 1, 5)

array([ 1.25892541,  2.11348904,  3.54813389,  5.95662144, 10.        ])

In [68]:
# 전치연산 (행과 열을 바꾸는 작업)
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
a.ndim, a.shape

(2, (2, 3))

In [71]:
a.T # transpose(전치행렬)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
a2 = a.T
a2.ndim, a2.shape

(2, (3, 2))

In [73]:
a.flatten(), a.ravel()

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 4, 5, 6]))

In [74]:
a.ndim, a.flatten(), a.ndim

(2, array([1, 2, 3, 4, 5, 6]), 2)

In [75]:
t = np.arange(30).reshape(3,5,2)
t

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [76]:
t.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [80]:
x = np.arange(5)
print(x, x.ndim, x.shape)
x2 = x[:, np.newaxis]
print(x2, x2.ndim, x2.shape)
x3 = x[np.newaxis, :]
print(x3, x3.ndim, x3.shape)

[0 1 2 3 4] 1 (5,)
[[0]
 [1]
 [2]
 [3]
 [4]] 2 (5, 1)
[[0 1 2 3 4]] 2 (1, 5)
