<a href="https://colab.research.google.com/github/JaejinLee1215/DataAnalysis/blob/main/JaejinLee1215/ch05_01%2B02_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
#!pip install numpy
import numpy as np # 규칙, 규약

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array((1, 2, 3))

array([1, 2, 3])

In [4]:
np.array(range(1, 4))

array([1, 2, 3])

In [6]:
np.array([c for c in "123"])

array(['1', '2', '3'], dtype='<U1')

In [7]:
np.array([int(c) for c in "123"])

array([1, 2, 3])

In [8]:
arr = np.array([1, 2, 3])

In [9]:
type(arr) # n-dimentinal array : n개 이상의 차원을 가진 배열

numpy.ndarray

# 벡터화 연산

In [12]:
a = list(range(10)) # 0~9 까지 1의 증가폭
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
a + 10 # 리스트와 int 간의 덧셈 불가

TypeError: ignored

In [14]:
a + [10] # 10이라는 요소(elemnet)가 추가

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [15]:
a * 2 # 리스트 요소들이 정수 n배 만큼 늘어남

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
[v for v in a] # 리스트 컴프리헨션

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
[v + 2 for v in a]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [18]:
[v * 2 for v in a]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [30]:
arr = np.arange(10) # np.array(range(10)) 이랑 같다.
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr + 2 # 배열(np.ndarray)에서 산술 연산자는 각각의 원소들에 대해서 계산 진행

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
arr + np.ones_like(arr) * 2 # 본질적인 의미

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
np.ones_like(arr) * 2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [34]:
arr + np.ones_like(arr) * 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [36]:
(((arr * 5) // 2) -1 ) % 7 # 산술 연산자처럼 가능

array([6, 1, 4, 6, 2, 4, 0, 2, 5, 0])

In [37]:
arr == 5

array([False, False, False, False, False,  True, False, False, False,
       False])

In [38]:
arr[arr == 5]

array([5])

In [39]:
arr[arr > 5] # 비교 연산처럼 가능

array([6, 7, 8, 9])

In [40]:
np.where(arr > 5)

(array([6, 7, 8, 9]),)

In [41]:
arr2 = np.arange(6, 25, 2)
arr2

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [42]:
np.where(arr2 % 3 == 0) # 불리언 인덱싱

(array([0, 3, 6, 9]),)

In [43]:
arr2[np.where(arr2 % 3 == 0)] #정수 인덱싱 # arr2[arr2 % 3 == 0] 과 같음

array([ 6, 12, 18, 24])

In [44]:
arr2[[0] * 5] # 정수 인덱싱은 커스텀 하기 편하다

array([6, 6, 6, 6, 6])

In [46]:
arr[(arr > 5) & (arr % 2 == 0)] # 논리 연산자

array([6, 8])

In [47]:
arr[(arr > 5) | (arr % 2 == 0)] # 논리 연산자

array([0, 2, 4, 6, 7, 8, 9])

```
! - bang(뱅)Exclamation Point(엑스클러메이션 포인트)
# - Crosshatch(크로스해치), Sharp(샵), Pound Sign(파운드사인)
$ - Dollar Sign (달러사인)
% - Percent Sign(퍼센트사인)
@ - At Sign (앳 사인), Commercial At(커머셜 앳)
& - Ampersand(앰퍼샌드) snowman
' - single quote(싱글쿼트) Apostrophe(어퍼스트로피), single quotation mark
" - double quote(더블쿼트)Quotation Mark(쿼테이션마크) , Double Quotation Mark
* - Asterisk(애스터리스크)
. - Period(피리어드), Full Stop(풀스탑)
/ - Slash (슬래시), Virgule(버귤)
\ - Back Slash(백슬래시)
: - Colon (콜론)
; - Semicolon(세미콜론)
^ - Circumflex(서컴플렉스), Caret(캐럿)
`(<<~이랑 같이 있는 넘) - Back Quote(백쿼트)Grave(그레이브)
{} - Brace(브레이스) (중괄호) curly braces/curly brackets
[] - Bracket(브래킷) (대괄호) brackets/square brackets
() - Parenthesis(퍼렌씨시스) (괄호)
| - Vertical Bar(버티컬바)
~ - Tilde (틸드)
= - Equal sign(이퀄사인)
+ - Plus Sign(플러스사인)
- - Minus Sign(마이너스사인)Hyphen(하이픈),Dash(대시)
_ - Underscore(언더스코어),Underline(언더라인)
< - Less Than Sign(레스댄 사인), Left Angle Bracket(레프트 앵글브래킷)
> - Greater Than Sign(그레이터댄 사인), Right Angle Bracket(라이트 앵글 브래킷)
? - Question Mark(물음표)
```

In [48]:
# ndaraay 
np.array([[1, 2, 3, 4],[1, 2, 3, 4]]) # 행들 간의 길이(열의 크기)가 같아야함

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [49]:
np.array([[1, 2, 3, 4],[1, 2, 3]]) # 생성이 되는 것처럼 보이지만 구조로써 만들어질 수 없다.

<ipython-input-49-7c158cab1420>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, 2, 3, 4],[1, 2, 3]])


array([list([1, 2, 3, 4]), list([1, 2, 3])], dtype=object)

In [51]:
a1 = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [52]:
a1[1, 1]

2

In [53]:
a2 = np.array([[1, 2, 3, 4],[1, 2, 3]]) # 열의 크기가 다름
a2[1, 1] # 인덱싱을 할 수 없다.

<ipython-input-53-2f78ec983ede>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = np.array([[1, 2, 3, 4],[1, 2, 3]])


IndexError: ignored

In [54]:
a1.ndim, a1.shape # 차원, 행렬의 모양

(2, (2, 4))

In [55]:
a2.ndim, a2.shape # 차원, 행렬의 모양
# 2차원 배열로 만들었지만 열의 크기가 달라서 1차원으로 인식

(1, (2,))

In [56]:
m = np.array([[1,2],[3,4]])
m2 = np.array((range(2,4), range(5,7)))
print(m)
print(m2)

[[1 2]
 [3 4]]
[[2 3]
 [5 6]]


In [57]:
t = np.array([
    [
        [1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]
    ],
    [
        [1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]
  ],
])
t

array([[[1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]],

       [[1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]]])

In [58]:
t.ndim, t.shape

(3, (2, 3, 4))

In [59]:
a = np.arange(10).reshape(2, 4) # 10이 나와야하는데 2*4 = 8
# shape에 들어가는 매개변수들은 모두 곱했을 때 전체 원소 크기가 되어야한다.

ValueError: ignored

In [62]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [63]:
b = a
b[0,1] = 9

In [64]:
print(a)
print(b)

[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [66]:
c = a.copy()
c[2, 1] = -99
print(a)
print(c)

[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[  0   9]
 [  2   3]
 [  4 -99]
 [  6   7]
 [  8   9]]


In [67]:
a = np.arange(1, 100, 25)
a

array([ 1, 26, 51, 76])

In [69]:
a[2], a[-1], a[len(a)-1]

(51, 76, 76)

In [70]:
a[3], a[-1], a[len(a)-1]

(76, 76, 76)

In [71]:
a[3], a[-1], a[a.shape[0] - 1]

(76, 76, 76)

In [73]:
# , (comma) [][]
m = np.arange(6).reshape((2, 3))
m

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
print(m)
m[0, 0],  m[0, 1]

[[0 1 2]
 [3 4 5]]


(0, 1)

In [76]:
m.ndim, m.shape

(2, (2, 3))

In [77]:
m[-2, 0],  m[-2, -1]

(0, 2)

In [78]:
m[m.shape[0]-2, 0], m[m.shape[0]-2, m.shape[1]-1]

(0, 2)

In [82]:
d1, d2 = m.shape # d1 : 행 차원의 길이, d2: 열 차원의 길이
row_length, column_length = m.shape

In [83]:
m[d1-2, 0], m[d1-2, d2-1]
m[row_length-2, 0], m[row_length-2, column_length-1]

(0, 2)

In [85]:
# :
print(a)
a[1:2]

[ 1 26 51 76]


array([26])

In [86]:
# 1차원의 배열의 슬라이싱 = 리스트의 슬라이싱과 같다
a2 = np.arange(0, 100, 10)
a2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [91]:
a2[1:10:2], a2[10::-1], a2[::-1], a2[:]

(array([10, 30, 50, 70, 90]),
 array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0]),
 array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [92]:
m

array([[0, 1, 2],
       [3, 4, 5]])

In [93]:
m[0], m[0,:] # 행은 인덱스로 쓰고 열은 슬라이싱

(array([0, 1, 2]), array([0, 1, 2]))

In [94]:
m[:,0]
print(m[:,0:1])

[[0]
 [3]]


* https://www.w3schools.com/python/numpy/default.asp
* 학습 참고용

# 배열의 자료형

In [96]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [98]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [99]:
x = np.array([1, 2.0, 3])
x.dtype # 실수는 정수를 포함한다.

dtype('float64')

In [100]:
x = np.array([1, 2.0, "3"])
x.dtype

dtype('<U32')

In [101]:
x = np.array([1, 2, 3], dtype='i')
x2 = np.array([1, 2, 3], dtype=int)
print(x, x.dtype)
print(x2, x2.dtype)

[1 2 3] int32
[1 2 3] int64


In [102]:
x = np.array([1, 2, 3], dtype='f')
x2 = np.array([1, 2, 3], dtype=float)
print(x, x.dtype)
print(x2, x2.dtype)

[1. 2. 3.] float32
[1. 2. 3.] float64


In [103]:
x = np.array([1, 2, 3.5], dtype='i')
print(x, x.dtype)

[1 2 3] int32


In [104]:
x = np.array([1, 2, "안녕"], dtype='i')
print(x, x.dtype)

ValueError: ignored

In [107]:
a = np.zeros(5)
b = np.array([0, 1, 0, 1, 0]) # 0 / 0 -> nan : not a number -> na라 부르기도 한다.
a / b, b / a # inf : infinity 무한

<ipython-input-107-077e67a3df68>:3: RuntimeWarning: invalid value encountered in true_divide
  a / b, b / a
<ipython-input-107-077e67a3df68>:3: RuntimeWarning: divide by zero encountered in true_divide
  a / b, b / a


(array([nan,  0., nan,  0., nan]), array([nan, inf, nan, inf, nan]))

In [108]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [110]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [111]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [112]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [113]:
np.ones_like(a)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [114]:
np.empty((2,5))

array([[3.07454047e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 9.04779691e-043],
       [1.25774683e-075, 7.61482389e+169, 5.49417274e-090,
        5.40267237e-038, 2.21352203e+161]])

In [115]:
np.linspace(10, 100, 5) # 10과 100사이를 5로 나눈다., y = x

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [117]:
np.logspace(0.1, 1, 5) # y = logx

array([ 1.25892541,  2.11348904,  3.54813389,  5.95662144, 10.        ])

In [118]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
A.ndim, A.shape

(2, (2, 3))

In [120]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [121]:
A2 = A.T
A2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [122]:
A2.ndim, A2.shape

(2, (3, 2))

In [123]:
A, a.flatten, A.ravel()

(array([[1, 2, 3],
        [4, 5, 6]]), <function ndarray.flatten>, array([1, 2, 3, 4, 5, 6]))

In [125]:
t = np.arange(30).reshape(3, 5, 2)
t

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [126]:
t.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [130]:
x = np.arange(5)
print(x, x.ndim, x.shape)
x2 = x[:, np.newaxis] # 차원 추가
print(x2, x2.ndim, x2.shape)
x3 = x[np.newaxis,:] # 차원 추가
print(x3, x3.ndim, x3.shape)

[0 1 2 3 4] 1 (5,)
[[0]
 [1]
 [2]
 [3]
 [4]] 2 (5, 1)
[[0 1 2 3 4]] 2 (1, 5)
