<a href="https://colab.research.google.com/github/JaejinLee1215/DataAnalysis/blob/main/JaejinLee1215/ch05_02%2B03%2B04_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [138]:
arr1 = np.arange(1, 4) # 1, 2, 3
arr2 = np.arange(4, 7) # 4, 5, 6
np.concatenate([arr1, arr2], axis = 0)

array([1, 2, 3, 4, 5, 6])

In [139]:
np.concatenate([arr1, arr2, arr1, arr2])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [140]:
arr1 = arr1.reshape(3, 1)
arr2 = arr2.reshape(3, 1)

np.concatenate([arr1, arr2])
np.concatenate([arr1, arr2], axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [141]:
np.concatenate([arr1, arr2], axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))
print(a1)
print(a2)
np.hstack((a1, a2))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [15]:
# b1 = np.ones((2, 3))
b1 = np.ones_like(a1)
b2 = np.zeros((3, 3))
np.vstack((b1, b2))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
c1 = np.ones((3, 4))
c2 = np.zeros_like(c1)
np.dstack((c1, c2)) # 행, 열 길이 같고, 가장 마지막(안쪽의) 차원이 1증가하면서 합쳐진다.

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [17]:
# c = np.stack([c1, c2])
c = np.stack([c1, c2], axis = 0) # 행 기준
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
np.stack([c1, c2], axis = -1) # 차원을 추가하면서 합쳐지는 (dstack)

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [19]:
np.stack([c1, c2], axis = 1) # 열 기준

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [20]:
# r_ -> hstack. 1, 2, 3  / 4, 5, 6
np.r_[np.arange(1, 4), np.arange(4, 7)]

array([1, 2, 3, 4, 5, 6])

In [22]:
np.r_[np.arange(1, 4), np.arange(4, 7), np.arange(4, 7)]

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [23]:
np.c_[np.arange(1, 4), np.arange(4, 7)]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
np.arange(1, 4)[:, np.newaxis], np.arange(4, 7)[:, np.newaxis]

(array([[1],
        [2],
        [3]]), array([[4],
        [5],
        [6]]))

In [25]:
np.concatenate((np.arange(1, 4)[:, np.newaxis], np.arange(4, 7)[:, np.newaxis]), axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
a = np.arange(6).reshape(3, -1)
print(np.tile(a, 3)) # 모양을 지키면서 반복
print(np.repeat(a, 3)) # flattern 시킨 다음에, 각 원소들을 그 위치에 반복

[[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [4 5 4 5 4 5]]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [29]:
arr = np.arange(7) # 0, 1, 2, 3, 4, 5, 6
arr

array([0, 1, 2, 3, 4, 5, 6])

In [30]:
np.array_split(arr, 3) # array_split : 3등분 분할

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

In [33]:
arr = np.arange(6)
np.split(arr, 3) # split: 엄격하게 약수로 맞게 입력해야 분할

[array([0, 1]), array([2, 3]), array([4, 5])]

In [34]:
arr = np.arange(1, 19).reshape(-1, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [36]:
# np.array_split(arr, 3) # 행 방향으로 짜름
np.array_split(arr,3, axis=0) # 행 방향으로 짜름

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]), array([[13, 14, 15],
        [16, 17, 18]])]

In [35]:
np.array_split(arr,3, axis=1) # 열 방향으로 짜름

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [37]:
# 브로드캐스팅 : 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방법
x = np.arange(5)
x + 1

array([1, 2, 3, 4, 5])

In [38]:
x + np.ones_like(x) * 1 # 이 과정이 일어나는 것

array([1, 2, 3, 4, 5])

In [39]:
x + 10

array([10, 11, 12, 13, 14])

In [40]:
x + np.ones_like(x) * 10

array([10, 11, 12, 13, 14])

In [41]:
x + np.full_like(x, 10)

array([10, 11, 12, 13, 14])

In [42]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [43]:
y = np.arange(5).reshape(-1, 1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [44]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [45]:
x = np.arange(1, 5) # 1, 2, 3, 4

In [46]:
np.sum(x), x.sum()

(10, 10)

In [47]:
x.min(), x.max()

(1, 4)

In [48]:
x.argmin(), x.argmax()

(0, 3)

In [50]:
x.mean()

2.5

In [53]:
np.median(x)

2.5

In [54]:
np.any(x > 4), np.any(x > 2)

(False, True)

In [55]:
np.all(x > 4), np.all(x > 2), np.all(x >= 0)

(False, False, True)

In [58]:
x = np.array(((1, 1), (2, 2)))
x

array([[1, 1],
       [2, 2]])

In [59]:
x.sum()

6

In [60]:
x.sum(axis=0) # 행 내부에 있는 열들간의 연산, 행의 대푯값(axis=0)

array([3, 3])

In [61]:
x.sum(axis=1) # 열 내부에 있는 행들간의 연산, 행의 대푯값(axis=1)

array([2, 4])

In [63]:
a = np.random.randint(1, 20, 12)
a

array([12,  9,  5, 14, 16,  1,  6, 17,  4, 19,  6, 15])

In [64]:
a = np.random.randint(1, 20, 12).reshape(3, -1)
a

array([[ 2, 11,  7,  5],
       [ 3, 12,  2,  6],
       [13,  9, 19,  3]])

In [65]:
np.sort(a) # 행을 그대로, 열들 간의 정리, axis = 0
np.sort(a, axis=1) # 행을 그대로, 열들 간의 정리, axis = 1
np.sort(a, axis=-1)

array([[ 2,  5,  7, 11],
       [ 2,  3,  6, 12],
       [ 3,  9, 13, 19]])

In [66]:
np.sort(a, axis=0) # 열을 그대로, 행들 간의 정리, axis=0

array([[ 2,  9,  2,  3],
       [ 3, 11,  7,  5],
       [13, 12, 19,  6]])

In [67]:
a.sort(axis=1) # in-place
a

array([[ 2,  5,  7, 11],
       [ 2,  3,  6, 12],
       [ 3,  9, 13, 19]])

In [146]:
np.argsort(a)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [147]:
np.argsort(a, axis=0)

array([[0, 1, 1, 0],
       [1, 0, 0, 1],
       [2, 2, 2, 2]])

In [72]:
x = np.random.randint(0, 100, 12).reshape(3, -1)
x

array([[11, 79, 99, 50],
       [81, 19, 76, 69],
       [34, 82, 69, 16]])

In [74]:
x[:, np.argsort(x[1])]

array([[79, 50, 99, 11],
       [19, 69, 76, 81],
       [82, 16, 69, 34]])

In [76]:
x = np.random.randint(-30, 30, 30)
x

array([  3,  26,  11, -22,  27,  28,   4,   1, -13,  -8,   4,  -5,   1,
        -1, -23, -15,   8,  13,  11,  -1,  18, -24, -14,   6, -19, -17,
       -26,   8,  17, -15])

In [77]:
len(x)

30

In [80]:
np.mean(x), x.mean()

(-0.5666666666666667, -0.5666666666666667)

In [81]:
np.var(x)

241.04555555555552

In [82]:
np.std(x)

15.525641872578264

In [83]:
np.max(x), np.min(x)

(28, -26)

In [84]:
np.median(x) # 짝수개일 경우, 두 값의 평균을 쓴다

1.0

In [88]:
np.quantile(x, 0), np.percentile(x, 0) # 최솟값

(-26, -26.0)

In [91]:
# 사분위수 => 1을 최대로 봤을 때의 비율수. 1/4, 2/4, 3/4...
# 백분위수는 100을 최대로 봤을 때의 값을 입력
np.quantile(x, 0.25), np.percentile(x, 25) # 1사분위수, 25백분위수

(-14.75, -14.75)

In [92]:
np.quantile(x, 2/4), np.percentile(x, 50) # 2사분위수, 50백분위수, 중앙값

(1.0, 1.0)

In [93]:
np.quantile(x, 3/4), np.percentile(x, 75) # 3사분위수, 75백분위수

(10.25, 10.25)

In [94]:
np.quantile(x, 4/4), np.percentile(x, 100) # 최댓값

(28.0, 28.0)

In [95]:
np.random.seed(0) # 이후 나오는 랜덤값들이 순서가 일치

In [96]:
np.random.rand(5) # 5개의 0과 1사이의 난수가 발생

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [97]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.random.shuffle(x)
x

array([0, 8, 7, 9, 1, 3, 5, 2, 4, 6])

In [101]:
np.random.choice(x, 5, replace=False) # x 배열 안의 있는 값 중에 5개를 추출(비복원)

array([4, 6, 1, 9, 0])

In [103]:
np.random.choice(5, 5, replace=False)

array([0, 4, 2, 1, 3])

In [104]:
np.random.choice(np.arange(1, 46), 6, replace=False)

array([23, 39, 17, 42, 31, 29])

In [107]:
np.random.choice(np.arange(1, 7), 6)
np.random.choice(np.arange(1, 7), 6, replace=True)

array([3, 6, 6, 6, 1, 2])

In [108]:
np.random.choice(np.arange(1, 7), 6, p = [0, 0, 0, 0.6, 0.2, 0.2])

array([5, 6, 5, 4, 5, 5])

In [109]:
# 표준 정규 분포는 평균이 0이고 분산이 1인 정규 분포를 말합니다. 
# 이때 분산은 표준 편차의 제곱으로 정의됩니다. 
# 즉, 표준 정규 분포에서 난수를 생성하면 대부분의 값이 0 근처에서 생성되며, 
# 값이 0에서 멀어질수록 발생하는 빈도가 낮아집니다.
np.random.randn(10) # 0 평균, 표준편차 -1 -2

array([-0.68658948,  0.01487332, -0.3756659 , -0.03822364,  0.36797447,
       -0.0447237 , -0.30237513, -2.2244036 ,  0.72400636,  0.35900276])

In [110]:
np.random.randn(3, 5)

array([[ 1.07612104,  0.19214083,  0.85292596,  0.01835718,  0.42830357],
       [ 0.99627783, -0.49114966,  0.71267817,  1.11334035, -2.15367459],
       [-0.41611148, -1.07089699,  0.22113881, -1.12305712, -1.05075796]])

In [111]:
np.random.randint(10) # 최소 0, 최대 low

0

In [114]:
np.random.randint(10, size = 100) # 최소 0, 최대 low, size = 100

array([5, 5, 5, 2, 5, 7, 7, 6, 1, 6, 7, 2, 3, 1, 9, 5, 9, 9, 2, 0, 9, 1,
       9, 0, 6, 0, 4, 8, 4, 3, 3, 8, 8, 7, 0, 3, 8, 7, 7, 1, 8, 4, 7, 0,
       4, 9, 0, 6, 4, 2, 4, 6, 3, 3, 7, 8, 5, 0, 8, 5, 4, 7, 4, 1, 3, 3,
       9, 2, 5, 2, 3, 5, 7, 2, 7, 1, 6, 5, 0, 0, 3, 1, 9, 9, 6, 6, 7, 8,
       8, 7, 0, 8, 6, 8, 9, 8, 3, 6, 1, 7])

In [112]:
np.random.randint(1, 10) # 최소 low, 최대 high

9

In [113]:
np.random.randint(1, 10, 100) # 최소 low, 최대 high, size

array([9, 4, 9, 3, 9, 5, 4, 1, 5, 4, 7, 9, 1, 9, 6, 1, 7, 6, 4, 2, 9, 1,
       5, 7, 6, 8, 9, 9, 3, 9, 7, 7, 2, 7, 9, 9, 4, 3, 4, 7, 4, 7, 6, 8,
       1, 9, 5, 7, 6, 9, 3, 4, 8, 6, 4, 5, 6, 4, 4, 8, 8, 4, 3, 4, 8, 8,
       6, 2, 3, 3, 9, 2, 6, 9, 5, 1, 3, 6, 6, 1, 9, 2, 2, 1, 4, 9, 9, 5,
       5, 1, 4, 8, 4, 3, 2, 2, 3, 2, 5, 3])

In [116]:
# 가격이 1만원 주식
price = 10000
# 일간 수익률 -> 기댓값(평균) 0, 표준편차 1%=0.01 (표준정규분포)
days = 250
daily_earning_rate = np.random.randn(days) / 100
# 250일 동안의 주가를 무작위로 생성
# 주가 -> 전일 가격 * (1 + 당일 수익률)
price_arr = np.empty(days)
for i, v in enumerate(daily_earning_rate):
    price *= (1 + v)
    print(price)
    price_arr[i] = price
    print(price_arr[i])
    print(price_arr)
price_arr

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
  9.63158380e+03  9.54230573e+03  9.48124328e+03  9.46081883e+03
  9.50630277e+03  9.66840298e+03  9.54848976e+03  9.53284801e+03
  9.62336821e+03  9.63808946e+03  9.70665496e+03  9.89617998e+03
  9.75411427e+03  9.88591247e+03  9.76213860e+03  9.86500731e+03
  9.91422089e+03  9.86810939e+03  9.85845892e+03  9.85510725e+03
  9.88641967e+03  9.90434091e+03  9.95001130e+03  9.99490740e+03
  9.83067158e+03  9.79236401e+03  9.77156846e+03  9.73127074e+03
  9.67045451e+03  9.65283807e+03  9.67319193e+03  9.49402063e+03
  9.42692909e+03  9.49053262e+03  9.50276855e+03  9.58826702e+03
  9.60945102e+03  9.54538470e+03  9.60736159e+03  9.54163038e+03
  9.59726613e+03  9.61860240e+03  9.54508226e+03  9.46866611e+03
  9.44657703e+03  9.42723282e+03  9.26242226e+03  9.38784318e+03
  9.08110267e+03  9.07926308e+03  9.02729877e+03  8.88646521e+03
  8.86460647e+03  8.83833840e+03  8.93146364e+03  8.91017812e+03
  8.90490957e+03  9.03802820e+03  8.93331765e+03  8.99

array([ 9975.89325249,  9958.33978878, 10059.06458401,  9783.38504998,
        9969.79862559,  9943.05416755,  9814.0077299 ,  9872.50440675,
        9787.07017911,  9591.30906328,  9615.90671877,  9619.95685189,
        9631.58380472,  9542.30572734,  9481.24328072,  9460.81882865,
        9506.3027694 ,  9668.40298175,  9548.48976306,  9532.84800719,
        9623.36820715,  9638.08945526,  9706.65496131,  9896.17997781,
        9754.11427473,  9885.91247221,  9762.13860297,  9865.00730672,
        9914.22089369,  9868.10939479,  9858.45891922,  9855.1072483 ,
        9886.41966936,  9904.34090697,  9950.01129537,  9994.90739535,
        9830.6715787 ,  9792.36401251,  9771.56846395,  9731.27073634,
        9670.45450576,  9652.83806972,  9673.19193369,  9494.02062846,
        9426.92908669,  9490.53262093,  9502.7685498 ,  9588.26701918,
        9609.45102458,  9545.3847021 ,  9607.36158618,  9541.63038484,
        9597.26613111,  9618.6024008 ,  9545.08225724,  9468.66610738,
      

In [117]:
x = np.random.randint(1, 10, 100)
x

array([8, 4, 9, 3, 5, 4, 2, 7, 6, 9, 5, 4, 7, 6, 4, 8, 9, 9, 4, 8, 9, 6,
       8, 3, 8, 9, 1, 8, 5, 9, 5, 5, 1, 5, 9, 1, 1, 5, 8, 4, 8, 8, 3, 3,
       2, 8, 1, 8, 6, 8, 2, 2, 3, 5, 2, 5, 6, 9, 3, 2, 7, 4, 1, 4, 6, 2,
       4, 8, 2, 2, 8, 5, 3, 1, 4, 3, 5, 1, 1, 4, 9, 4, 1, 5, 5, 1, 3, 6,
       6, 9, 3, 8, 4, 7, 2, 1, 3, 3, 6, 6])

In [118]:
np.unique(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.unique(x, return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([12, 10, 12, 13, 13, 10,  4, 15, 11]))

In [121]:
key, value = np.unique(x, return_counts = True)
print(key)
print(value)

[1 2 3 4 5 6 7 8 9]
[12 10 12 13 13 10  4 15 11]


In [123]:
# 2개의 시퀀스를, 인덱스를 기반으로 묶어줌 zip
list(zip(key, value))

[(1, 12),
 (2, 10),
 (3, 12),
 (4, 13),
 (5, 13),
 (6, 10),
 (7, 4),
 (8, 15),
 (9, 11)]

In [124]:
dict(zip(key, value))

{1: 12, 2: 10, 3: 12, 4: 13, 5: 13, 6: 10, 7: 4, 8: 15, 9: 11}

In [125]:
dict(list(zip(key, value)))

{1: 12, 2: 10, 3: 12, 4: 13, 5: 13, 6: 10, 7: 4, 8: 15, 9: 11}

In [127]:
dict(zip(*np.unique(x, return_counts=True))) # *의 의미

{1: 12, 2: 10, 3: 12, 4: 13, 5: 13, 6: 10, 7: 4, 8: 15, 9: 11}

In [120]:
np.unique(x, return_counts = True, return_inverse=True) # 이런 것도 있다...

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([7, 3, 8, 2, 4, 3, 1, 6, 5, 8, 4, 3, 6, 5, 3, 7, 8, 8, 3, 7, 8, 5,
        7, 2, 7, 8, 0, 7, 4, 8, 4, 4, 0, 4, 8, 0, 0, 4, 7, 3, 7, 7, 2, 2,
        1, 7, 0, 7, 5, 7, 1, 1, 2, 4, 1, 4, 5, 8, 2, 1, 6, 3, 0, 3, 5, 1,
        3, 7, 1, 1, 7, 4, 2, 0, 3, 2, 4, 0, 0, 3, 8, 3, 0, 4, 4, 0, 2, 5,
        5, 8, 2, 7, 3, 6, 1, 0, 2, 2, 5, 5]),
 array([12, 10, 12, 13, 13, 10,  4, 15, 11]))

In [129]:
x = np.random.randint(30, size = 10)
x

array([29,  3,  1, 16, 17, 16, 24, 24, 26,  5])

In [130]:
dict(zip(*np.unique(x, return_counts=True)))

{1: 1, 3: 1, 5: 1, 16: 2, 17: 1, 24: 2, 26: 1, 29: 1}

In [131]:
np.bincount(x, minlength=30)

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0,
       0, 0, 2, 0, 1, 0, 0, 1])

In [132]:
np.arange(30), np.bincount(x, minlength=30)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0,
        0, 0, 2, 0, 1, 0, 0, 1]))

In [134]:
dict(zip(np.arange(30), np.bincount(x, minlength=30)))

{0: 0,
 1: 1,
 2: 0,
 3: 1,
 4: 0,
 5: 1,
 6: 0,
 7: 0,
 8: 0,
 9: 0,
 10: 0,
 11: 0,
 12: 0,
 13: 0,
 14: 0,
 15: 0,
 16: 2,
 17: 1,
 18: 0,
 19: 0,
 20: 0,
 21: 0,
 22: 0,
 23: 0,
 24: 2,
 25: 0,
 26: 1,
 27: 0,
 28: 0,
 29: 1}

In [142]:
eval("1 + 1")

2

In [143]:
eval("len([1, 2, 3])")

3

In [144]:
eval("np.random.randint(5, 10, 10)")

array([8, 7, 7, 8, 6, 5, 6, 6, 9, 7])