<a href="https://colab.research.google.com/github/jaiwon880/DataAnalysis_23/blob/main/jaiwon880/ch05_02_%EB%B0%B0%EC%97%B4%EC%9D%98_%EC%83%9D%EC%84%B1%EA%B3%BC_%EB%B3%80%ED%98%952.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 배열의 생성과 변형

## Numpy의 자료형
* Numpy의 배열 즉, `ndarray` 클래스는 원소가 모두 같은 자료형이어야 함
* `array` 명령으로 배열을 만들 때 자료형을 명시적으로 적용하려면 `dtype` 인수를 사용
* 만약 `dtype` 인수가 없으면 주어진 데이터를 저장할 수 있는 자료형을 스스로 유추
* 만들어진 배열의 자료형을 알아내려면 `dtype` 속성을 사용 


In [ ]:
import numpy as np
x = np.array([1,2,3])
x.dtype
# int64 64는 바이트

dtype('int64')

In [ ]:
x = np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [ ]:
x = np.array([1,2.0])
x.dtype # 더 큰 타입의 인수로 결과값이 나옴

dtype('float64')

* `dtype` 인수
    * dtype 접두사로 시작하는 문자열
    * 접두사 뒤 오는 숫자 = 바이트 수 혹은 글자 수
    * 숫자 생략 시 운영체제에 따라 알맞은 크기 지정

|dtype 접두사|설명|사용 예|
|-|-|-|
|`b`|불리언|`b` (참 혹은 거짓)|
|`i`|정수|`i8` (64비트)|
|`u`|부호 없는 정수|`u8` (64비트)|
|`f`|부동소수점|`f8` (64비트)|
|`c`|복소 부동소수점|`c16` (128비트)|
|`O`|객체|`0` (객체에 대한 포인터)|
|`S`|바이트 문자열|`S24` (24 글자)|
|`U`|유니코드 문자열|`U24` (24 유니코드 글자)|

In [ ]:
# x = np.array([1,2,3], dtype="f") # f -> 32 기본값
x = np.array([1,2,3], dtype=float) # float -> 64 기본값
x.dtype

dtype('float64')

In [ ]:
x[0] + x[1]

3.0

In [ ]:
x = np.array([1,2,3], dtype="U")
x.dtype

dtype('<U1')

In [ ]:
x[0] + x[1]

'12'

## Inf와 NaN
* Numpy에서는 무한대를 표현하기 위한 `np.inf`(infinity)와 정의할 수 없는 숫자를 나타내는 `np.nan(not a number)`을 사용


In [ ]:
# 1을 0으로 나누려고 할 때, 0을 0으로 나누려고 시도...
np.array([0,1, -1, 0] / np.array([1,0,0,0]))

<ipython-input-13-3818f67c36fd>:2: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1, -1, 0] / np.array([1,0,0,0]))
<ipython-input-13-3818f67c36fd>:2: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1, -1, 0] / np.array([1,0,0,0]))


array([  0.,  inf, -inf,  nan])

In [ ]:
# 0에 대한 로그 값을 계산
np.log(0) 

<ipython-input-15-2947364c5d70>:2: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

## 배열 생성
* `zeros`, `ones`
* `zeros_like`, `ones_like`
* `empty`
* `arange`
* `linspace`, `logspace`

### zeros : 크기가 정해져 있고 모든 값이 0인 배열 생성

In [ ]:
# 정수를 넣으면 해당 크기의 0으로 채워진 1차원 배열 생성
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
# 튜플을 넣으면 해당 크기의 0으로 채워진 다차원 배열 생성
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# dtype 인수 명시 시 해당 자료형 원소 타입 부여
c = np.zeros((5,2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [ ]:
# 문자열 배열도 가능하지만, 모든 원소의 문자열 크기가 같아야 함
# 만약 더 큰 크기의 문자열을 할당하면 잘림
d = np.zeros(5, dtype="U4") # 빈 문자로 5개 찬, 배열 -> 배열은 문자열을 넣었을 때 최대길이 4
d

array(['', '', '', '', ''], dtype='<U4')

In [ ]:
d[0] = "abc"
d[1] = "abcd"
d[2] = ("abcd"+"e").upper() # "ABCDE" # 4개가 넘어가면 알아서 삭제됨
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

### ones : 1로 초기화된 배열을 생성 

In [ ]:
e = np.ones((2,3,4,5), dtype="f8")
e

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

### ones_like, zeros_like : 다른 배열과 같은 크기의 배열을 생성

#### 왜 존재? ones는 곱하기 할 때 배열 활용하려고

In [ ]:
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
g = np.zeros_like(b, dtype="f")
g

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

### empty : 값 초기화 없이 배열을 생성 (시간 절약)
* 기존 메모리에 저장되어 있던 값이 있음
* 배열의 원소 값을 미리 알 수 없음

In [ ]:
g = np.empty((4,3))
g

array([[2.0952415e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

### arange : 특정 규칙에 따라 증가하는 수열을 만듦 (like `range`)

In [ ]:
np.arange(0,10), np.array(range(10))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
np.arange(3,20,2, dtype="f"), np.array(range(3,20,2), dtype="f")

(array([ 3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32),
 array([ 3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32))

### linspace, logspace : 선형 구간 또는 로그 구간을 지정한 구간의 수만큼 분할

In [ ]:
np.linspace(0, 100, 5) # 시작, 끝 포함, 마지막 변수는 분할 수

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.logspace(0.1, 1, 10) 

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## 전치 연산 (transpose)
* 2차원 배열에서 행과 열을 바꾸는 작업
* 배열의 `T` **속성**

In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])
A, A.ndim, A.shape

(array([[1, 2, 3],
        [4, 5, 6]]), 2, (2, 3))

In [ ]:
A2 = A.T
A2, A2.ndim, A2.shape

(array([[1, 4],
        [2, 5],
        [3, 6]]), 2, (3, 2))

## 배열의 크기 변형 (`reshape`)

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 사용하는 원소의 갯수가 정해져 있기 때문에
# reshape 명령의 형태 튜플 원소 중 하나는 -1으로 대체 가능
# -1을 넣으면 해당 숫자는 다른 값을 통해 계산되어서 사용
a.reshape(3, -1) 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(2, 2, -1) # batch 일괄처ㄹㅣ

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

## 배열 평탄화 (`flatten`, `ravel`)
* 다차원 배열을 1차원으로 변환

In [ ]:
a.reshape(len(a))  # a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 같은 배열에 대해 차원만 1차원 증가 (`newaxis`)

In [ ]:
x = np.arange(5)
print(x, x.ndim, x.shape)
x2 =x[:,np.newaxis]
print(x2, x2.ndim, x2.shape)
x3 = x[np.newaxis,:]
print(x3, x3.ndim, x3.shape)

[0 1 2 3 4] 1 (5,)
[[0]
 [1]
 [2]
 [3]
 [4]] 2 (5, 1)
[[0 1 2 3 4]] 2 (1, 5)


## 배열 연결
* 행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하여 더 큰 배열을 생성 (concatenate)
    * `hstack`
    * `vstack`
    * `dstack`
    * `stack`
    * `r_`
    * `c_`
    * `tile`

### `concatenate`

In [7]:
import numpy as np
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)
print(np.array(list(arr1)+list(arr2)))
np.concatenate((arr1,arr2))

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [14]:
arr1 = arr1.reshape(3, 1)
arr2 = arr2.reshape(3, 1)

print(arr1)
print(arr2)

x1 = np.concatenate((arr1,arr2), axis = 0) # 행 방향 0 열 방향 1
print(x1,x1.ndim, x1.shape)  # 차원은 축이다

x2 = np.concatenate((arr1,arr2), axis = 1) # 행 방향 0 열 방향 1
print(x2,x2.ndim, x2.shape)  # 차원은 축이다

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 2 (6, 1)
[[1 4]
 [2 5]
 [3 6]] 2 (3, 2)


### `hstack`
* 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만듦
* 연결할 배열은 하나의 리스트에 담아야 함

In [15]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [20]:
np.hstack((a1,a2)) # 행을 기준으로 안 바꿈, 열을 늘림

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [23]:
ha = np.hstack((a1,a2)) # 행(axis=0)으로 합쳐서 열이 변화함
ha, ha.ndim, ha.shape 

(array([[1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]]), 2, (2, 5))

In [48]:
np.concatenate((a1, a2), axis = 1) #열로 합쳐서 행(axis=0)이 변화함

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [49]:
np.hstack(np.full((4,4),i) for i in range(10))

<ipython-input-49-160e784a3ac6>:1: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  np.hstack(np.full((4,4),i) for i in range(10))


array([[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
        5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9],
       [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
        5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9],
       [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
        5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9],
       [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
        5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9]])

### `vstack`
* 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 만듦
* 연결할 배열은 하나의 리스트에 담아야 함

In [22]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
a2 = np.zeros((3,3))
a2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
va = np.vstack((a1,a2)) 
va, va.ndim, va.shape

(array([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]), 2, (5, 3))

In [46]:
np.concatenate((a1,a2),axis =0)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.vstack(np.full((4,4),i) for i in range(10))

<ipython-input-47-1eb03a6eaa99>:1: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  np.vstack(np.full((4,4),i) for i in range(10))


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

*이탤릭체 텍스트*### `dstack`
* 제3의 축 즉, 행이나 열이 아닌 깊이(depth) 방향으로 배열을 합침
* 가장 안쪽의 원소의 차원이 증가, 즉 가장 내부의 숫자 원소가 배열이 됨

In [33]:
a1 = np.ones((3,4))
a1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
a2 = np.zeros((3,4))
a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
da = np.dstack((a1,a2))
da, da.ndim, da.shape

(array([[[1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.]],
 
        [[1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.]],
 
        [[1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.]]]), 3, (3, 4, 2))

In [43]:
# np.concatenate((a1,a2), axis=2)
np.concatenate((a1[:,:,np.newaxis]), (a2[:,:,np.newaxis]),axis=2)

TypeError: ignored

In [45]:
np.dstack(np.full((4,4),i) for i in range(10))

<ipython-input-45-21222da8e90f>:1: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  np.dstack(np.full((4,4),i) for i in range(10))


array([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

### `stack`
* `dstack`의 기능을 확장한 것으로 `dstack`처럼 마지막 차원으로 연결하는 것이 아니라 사용자가 지정한 차원(축으로) 배열을 연결
* axis 인수(디폴트 0)를 사용하여 연결후의 회전 방향을 정함
* 디폴트 인수값은 0이고 가장 앞쪽에 차원이 생성. 즉, 배열 두 개가 겹치게 되므로 연결하고자 하는 배열들의 크기가 모두 같아야 함

In [50]:
arr_info = lambda arr:(arr,arr.ndim, arr.shape)

In [51]:
c = np.stack([a1,a2])
print(arr_info(a1))
print(a2)
print(c)

(array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]]), 2, (3, 4))
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


* `axis` 인수가 1이면 두번째 차원으로 새로운 차원이 삽입

In [52]:
c = np.stack([a1,a2], axis=1)
print(arr_info(a1))
print(a2)
print(c)

(array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]]), 2, (3, 4))
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]


In [53]:
c = np.stack([a1,a2], axis=2)  # newaxis , 축 위치가 바뀜
print(arr_info(a1))
print(a2)
print(c)

c.ndim

(array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]]), 2, (3, 4))
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


3

### `r_`
* `hstack` 명령과 비슷하게 배열을 좌우로 연결
* 다만 메서드임에도 불구하고 소괄호(parenthesis, `()`)를 사용하지 않고 인덱싱과 같이 대괄호(bracket, `[]`)를 사용
* 이런 특수 메서드를 인덱서(indexer)라고 함

In [56]:
np.r_[np.arange(1,4),np.arange(4,7)] # 끝점 미포함

array([1, 2, 3, 4, 5, 6])

In [57]:
np.r_[np.arange(1,5).reshape(2,2),np.arange(4,8).reshape(2,2)] # 끝점 미포함

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

### `c_`
* 배열의 차원을 증가시킨 후 좌우로 연결

In [58]:
np.c_[np.arange(1,4),np.arange(4,7)]

array([[1, 4],
       [2, 5],
       [3, 6]])

### `tile`
* 동일한 배열을 반복하여 연결

In [61]:
a = np.arange(6).reshape(2, -1)
arr_info(a)


(array([[0, 1, 2],
        [3, 4, 5]]), 2, (2, 3))

In [62]:
np.tile(a,2) # hstack 반복

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [63]:
np.tile(a,(3,2)) # vstack, hstack

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

## 💡 연습문제 4
```
array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])
```

In [84]:
a = np.full(3,0,dtype="f")
a

array([0., 0., 0.], dtype=float32)

In [87]:
b = np.full(2,1, dtype="f")
# b = np.tile(np.ones(1, dtype="f"),2)
b

array([1., 1.], dtype=float32)

In [90]:
# np.concatenate((a,b))
c = np.hstack((a,b))
# np.r_[a,b]
c

array([0., 0., 0., 1., 1.], dtype=float32)

In [91]:
d = np.tile(c,(3,1))
d

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]], dtype=float32)

In [93]:
e = np.arange(10,160, 10, dtype="f")
# np.arange(1,16, dtype="f") * 10
# (np.arange(15, dtype="f") +1 ) * 10
e

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.,
       120., 130., 140., 150.], dtype=float32)

In [94]:
# f = e.reshape(3,5)
# f = e.reshape(3,-1)
f = e.reshape(-1,5)
f

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]], dtype=float32)

In [98]:
g = np.concatenate((d,f), axis=0)
# g = np.vstack([d,f])
g

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]], dtype=float32)

In [99]:
h = np.tile(g,(2,1))
h

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]], dtype=float32)

## 배열 분할

In [102]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [103]:
newarr = np.split(arr,3)
newarr = np.array_split(arr,3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [105]:
arr = np.arange(1, 19).reshape(-1, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [108]:
# a = np.array_split(arr,3)
a = np.array_split(arr,3,axis=0)
a

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]), array([[13, 14, 15],
        [16, 17, 18]])]

In [109]:
b = np.array_split(arr,3,axis=1)
b

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

# 배열의 연산

## 벡터화 연산 (vectorized operation)
* 명시적으로 반복문을 사용하지 않고도 배열의 모든 원소에 대해 반복 연산을 할 수 있음
* 선형 대수 공식과 동일한 아주 간단한 파이썬 코드를 작성할 수 있음

<br>
$$
x = \begin{bmatrix}1\\2\\3\\⋯\\10000\end{bmatrix},\quad
y = \begin{bmatrix}10001\\10002\\10003\\⋯\\20000\end{bmatrix}
$$

<br>
$$
z = x + y
$$

<br>
$$
\begin{bmatrix}1\\2\\3\\⋯\\10000\end{bmatrix}
+ \begin{bmatrix}10001\\10002\\10003\\⋯\\20000\end{bmatrix}
= \begin{bmatrix}1+10001\\2+10002\\3+10003\\⋯\\10000+20000\end{bmatrix}
= \begin{bmatrix}10002\\10004\\10006\\⋯\\30000\end{bmatrix}
$$



In [ ]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [ ]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: user 6.36 ms, sys: 10 µs, total: 6.37 ms
Wall time: 12.9 ms


In [ ]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [ ]:
%%time
z = x + y

CPU times: user 646 µs, sys: 0 ns, total: 646 µs
Wall time: 505 µs


In [ ]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [ ]:
# 사칙 연산뿐 아니라 비교 연산과 같은 논리 연산도 벡터화 연산이 가능
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [ ]:
a == b

array([False,  True, False,  True])

In [ ]:
a >= b

array([False,  True,  True,  True])

In [ ]:
# 배열의 각 원소를 일일히 비교하는 것이 아닌 배열의 모든 원소가 다 같은지 알고 싶다면 all 명령 사용
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [ ]:
np.all(a == b)

False

In [ ]:
np.all(a == c)

True

In [ ]:
# 지수 함수, 로그 함수 등의 수학 함수도 벡터화 연산을 지원
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
10 ** a

array([    1,    10,   100,  1000, 10000])

In [ ]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

## 스칼라와 벡터/행렬의 곱셈

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [ ]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅
* 백터(또는 행렬)끼리 덧셈 혹은 뺄셈을 하려면 두 벡터(또는 행렬)의 크기가 같아야 함
* Numpy에선 서로 다른 크기를 가진 두 배열의 사칙 연산 지원 = 브로드캐스팅(broadcasting)
> 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방법

<br>
$$
x = \begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix},\quad 
x + 1 = \begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix} + 1 = ?
$$
<br>
$$
\begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix} + 1
= \begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix}
+ \begin{bmatrix}1\\1\\1\\1\\1\end{bmatrix}
= \begin{bmatrix}1\\2\\3\\4\\5\end{bmatrix}
$$

In [ ]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [ ]:
x + y

array([1, 2, 3, 4, 5])

In [ ]:
x + 1

array([1, 2, 3, 4, 5])

In [ ]:
# 2차원 이상에서도 적용됨
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [ ]:
y = np.arange(3)
y

array([0, 1, 2])

In [ ]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

## 차원 축소 연산 (dimension reduction)
> 행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 각 행에 처리된 연산으로 한 차원 낮은 벡터를 구성하게 하는 연산
* 최대/최소 : `min`, `max`, `argmin`, `argmax`
* 통계 : `sum`, `mean`, `median`, `std`, `var`
* 불리언 : `all`, `any`

In [ ]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [ ]:
np.sum(x), x.sum()

(10, 10)

In [ ]:
x = np.array([1, 3, 2])

In [ ]:
x.min(), x.max()

(1, 3)

In [ ]:
x.argmin()  # 최솟값의 위치

0

In [ ]:
x.argmax()  # 최댓값의 위치 

3

In [ ]:
x = np.array([1, 2, 3, 1])

In [ ]:
x.mean()

1.75

In [ ]:
np.median(x)

1.5

In [ ]:
np.all([True, True, False])

False

In [ ]:
np.any([True, True, False])

True

In [ ]:
a = np.zeros((100, 100), dtype='i')
a

NameError: ignored

In [ ]:
np.any(a != 0)

False

In [ ]:
np.all(a == a)

True

In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [ ]:
((a <= b) & (b <= c)).all()

True

* 연산의 대상이 2차원 이상인 경우에는 어느 차원으로 계산을 할 지를 axis 인수를 사용하여 지시
* axis=0인 경우는 열 연산, axis=1인 경우는 행 연산. 디폴트 값은 axis=0.
* axis 인수는 대부분의 차원 축소 명령에 적용할 수 있음

In [ ]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [ ]:
x.sum()

6

In [ ]:
x.sum(axis=0)   # 열 합계 

array([3, 3])

In [ ]:
x.sum(axis=1)   # 행 합계 

array([2, 4])

## 💡 연습문제 5
실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값 도출
1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값

In [ ]:
a = np.arange(30, dtype='f').reshape((5,6))
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.]], dtype=float32)

In [ ]:
# 전체의 최댓값
a.max()

29.0

In [ ]:
# 각 행의 합
a.sum(axis=1)

array([ 15.,  51.,  87., 123., 159.], dtype=float32)

In [ ]:
# 각 행의 최댓값
a.max(axis=1)

array([ 5., 11., 17., 23., 29.], dtype=float32)

In [ ]:
# 각 열의 평균
a.mean(axis=0)

array([12., 13., 14., 15., 16., 17.], dtype=float32)

In [ ]:
# 각 열의 최솟값
a.min(axis=0)

array([0., 1., 2., 3., 4., 5.], dtype=float32)

## 정렬
* `sort` : 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열 생성
* 2차원 이상인 경우에는 행이나 열을 각각 따로따로 정렬
    * `axis=0` : 각각의 행을 따로따로 정렬
    * `axis=1` : 각각의 열을 따로따로 정렬 
    * `axis=-1` : 가장 안쪽(나중)의 차원 (default)

In [ ]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [ ]:
np.sort(a)  # axis=-1 또는 axis=1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [ ]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [ ]:
# sort 메서드는 해당 객체의 자료 자체가 변화하므로 주의
# 자체변화(in-place) 메서드 = 원본이 수정됨
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

* `argsort` : 자료 정렬이 아니라 순서만 알고 싶다면 사용

In [ ]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [ ]:
a[j]

array([12, 25, 38, 42])

In [ ]:
np.sort(a)

array([12, 25, 38, 42])

## 💡 연습문제 6
> 두 번째 행을 기준으로 각 열(column)을 재정렬
```
array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
```

In [ ]:
x = np.array([
    [1, 2, 3, 4],
    [46, 99, 100, 71],
    [81, 59, 90, 100]
])
x

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
x[:, np.argsort(x[1])]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

# 기술 통계

## 기술 통계(descriptive statistics)
> 데이터 집합에 대해 통계를 계산
* 데이터의 개수(count)
* 평균(mean, average)
* 분산(variance)
* 표준 편차(standard deviation)
* 최댓값(maximum)
* 최솟값(minimum)
* 중앙값(median)
* 사분위수(quartile)

In [ ]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 데이터의 개수

In [ ]:
len(x)

26

## 표본 평균
* 우리가 일반적으로 아는 평균
* 통계용어로는 표본 평균(sample average, sample mean)
<br>
$
\bar{x} = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{x_i}
$
(𝑁은 데이터의 개수)

In [ ]:
np.mean(x)

4.8076923076923075

## 표본 분산
* 표본 분산(sample variance) : 데이터와 표본 평균간의 거리의 제곱의 평균
* 표본 분산이 작으면 데이터가 모여있는 것이고 크면 흩어져 있는 것
<br>
$
s^2 = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{(x_i-\bar{x})^2}
$

In [ ]:
np.var(x)

115.23224852071006

## 표본 표준편차
* 표본 표준편차(sample standard variance) : 표본 분산의 양의 제곱근 값 
<br>
$
s = \sqrt{s^2}
$

In [ ]:
np.std(x)

10.734628476137871

## 최댓값과 최솟값

In [ ]:
# 최댓값 (maximum) / 최솟값 (minimum)
np.max(x), np.min(x)

(23, -24)

## 중앙값
* 중앙값(median) : 데이터를 크기대로 정렬하였을 때 가장 가운데에 있는 수
* 만약 데이터의 수가 짝수이면 가장 가운데에 있는 두 수의 평균을 사용


In [ ]:
np.median(x)

5.0

## 사분위수
* 사분위수(quartile) : 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수
* 각각 1사분위수, 2사분위수, 3사분위수라고 함
* 1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%
* 따라서 2사분위수는 중앙값과 같음
* 때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 함
* 1사분위수는 25% 백분위수와 같음


In [ ]:
np.percentile(x, 0)  # 최솟값 

-24.0

In [ ]:
np.percentile(x, 25)  # 1사분위 수 

0.0

In [ ]:
np.percentile(x, 50)  # 2사분위 수 

5.0

In [ ]:
np.percentile(x, 75)  # 3사분위 수 

10.0

In [ ]:
np.percentile(x, 100)  # 최댓값 

23.0

# 난수 발생과 카운팅

## 시드 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아님
* 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성. 이런 시작 숫자를 시드(seed)라고 함
* 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 됨. 따라서 시드값은 한 번만 정해주면 됨.
* 시드는 보통 현재 시각 등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음 * 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있음
* 고정된 결과를 얻기 위해서 실습엔 시드를 설정

In [ ]:
np.random.seed(0) # 시드값 고정

### `rand` : 0과 1 사이의 난수를 발생

In [ ]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

## 데이터의 순서 변경

### `shuffle`
* 데이터의 순서를 변경
* 자체 변환(in-place) 함수 (원본에 영향)

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(x)
x

array([7, 8, 3, 6, 1, 5, 0, 4, 9, 2])

## 데이터 샘플링
* 표본선택 혹은 샘플링(sampling) : 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것

### `choice` : 샘플링에 사용
```
numpy.random.choice(a, size=None, replace=True, p=None)
```
* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능 (복원/비복원 추출)
* p : 배열. 각 데이터가 선택될 수 있는 확률

In [ ]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같음 

array([1, 4, 2, 3, 0])

In [ ]:
np.random.choice(5, 3, replace=False)  # 3개만 선택  (비복원 추출)

array([0, 1, 4])

In [ ]:
np.random.choice(5, 10)  # 반복해서 10개 선택 (복원 추출)

array([4, 2, 0, 0, 4, 0, 4, 1, 4, 1])

In [ ]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택 

array([3, 3, 3, 0, 3, 3, 2, 2, 3, 3])

## 난수 생성
* `rand` : 0부터 1 사이의 균일 분포
* `randn` : 표준 정규 분포
* `randint` : 균일 분포의 정수 난수

### `rand` : 0부터 1 사이에서 균일한 확률 분포로 실수 난수를 생성
* 숫자 인수는 생성할 난수의 크기
* 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [ ]:
np.random.rand(10)

array([0.32504723, 0.03842543, 0.63427406, 0.95894927, 0.65279032,
       0.63505887, 0.99529957, 0.58185033, 0.41436859, 0.4746975 ])

In [ ]:
np.random.rand(3, 5)

array([[0.6235101 , 0.33800761, 0.67475232, 0.31720174, 0.77834548],
       [0.94957105, 0.66252687, 0.01357164, 0.6228461 , 0.67365963],
       [0.971945  , 0.87819347, 0.50962438, 0.05571469, 0.45115921]])

### `randn` : 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

In [ ]:
np.random.randn(10)

array([-0.04411241, -0.36326702, -0.01234481,  0.04212149,  1.95929589,
       -0.1984257 ,  0.33053441, -1.43582841,  0.02752832,  1.12060466])

In [ ]:
np.random.randn(3, 5)

array([[-0.22403878, -0.42018339,  0.99982969,  0.43103415, -0.65091287],
       [-1.49874039, -1.23063497,  0.19400719, -0.99838235, -0.3676376 ],
       [ 1.73719932,  0.59361275, -0.54236358, -1.71967238, -0.57890879]])

### `randint`
```
numpy.random.randint(low, high=None, size=None)
```
만약 `high`를 입력하지 않으면 0과 `low`사이의 숫자, `high`를 입력하면 `low`와 `high`는 사이의 숫자를 출력. `size`는 난수의 숫자

In [ ]:
np.random.randint(10, size=10)

array([2, 8, 4, 3, 0, 4, 3, 6, 9, 8])

In [ ]:
np.random.randint(10, 20, size=10)

array([10, 18, 15, 19, 10, 19, 16, 15, 13, 11])

In [ ]:
np.random.randint(10, 20, size=(3, 5))

array([[18, 10, 14, 19, 16],
       [15, 17, 18, 18, 19],
       [12, 18, 16, 16, 19]])

## 💡 연습문제 7
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 작성하라
2. 주사위를 100번 던져서 나오는 숫자의 평균
3. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [ ]:
# 1.
coin = np.array(['HEAD', 'TAIL'])
np.random.choice(coin, size=10, replace=True)

array(['TAIL', 'TAIL', 'HEAD', 'HEAD', 'HEAD', 'HEAD', 'TAIL', 'TAIL',
       'TAIL', 'HEAD'], dtype='<U4')

In [ ]:
# 2.
# dice = np.arange(1,7)
# np.random.choice(dice,100,replace=True).mean()
np.random.randint(1,7,100).mean()

3.66

In [ ]:
# 3.
earn = np.random.randn(250) / 100
earn

array([-0.00317543, -0.01632423, -0.00067134,  0.01489356,  0.00521304,
        0.00611927, -0.01341497,  0.00476898,  0.0014845 ,  0.00529045,
        0.00422629, -0.01359781, -0.00041401, -0.00757871, -0.00050084,
       -0.00897401,  0.0131247 , -0.00858972, -0.00898942,  0.00074586,
       -0.01077099, -0.00424663, -0.00829965,  0.01411172,  0.00785804,
       -0.0005747 , -0.00391217,  0.00940918,  0.00405204,  0.00498052,
       -0.00026192, -0.0168823 , -0.00112466, -0.0053249 ,  0.00645055,
        0.01011842, -0.00657951,  0.00468385,  0.01735879, -0.00667713,
        0.01681922, -0.00852586,  0.0002296 , -0.00011146,  0.00011499,
       -0.00837678, -0.00591183, -0.0066772 ,  0.00326963,  0.00330035,
        0.02225944,  0.01370989, -0.00509843,  0.0032487 ,  0.00997118,
        0.00030602, -0.00069642,  0.00051575,  0.00867277, -0.00848321,
       -0.00325669,  0.00470433,  0.00311447,  0.00239583, -0.00369801,
        0.00972536,  0.02133868,  0.00406415, -0.00193177,  0.00

In [ ]:
stock = np.empty(250)
price = 10000
for i, v in enumerate(earn):
    price *= (1 + v)
    stock[i] = price
stock

array([ 9968.24569061,  9805.52172515,  9798.93887103,  9944.87995133,
        9996.72298327, 10057.89564959,  9922.96930879,  9970.29178757,
        9985.09264399, 10037.91830117, 10080.34141693,  9943.27087728,
        9939.15428244,  9863.82832836,  9858.88811928,  9770.41436592,
        9898.64815922,  9813.6215047 ,  9725.40272392,  9732.65655233,
        9627.82619918,  9586.94035449,  9507.37214356,  9641.53752326,
        9717.30109408,  9711.71660794,  9673.72271651,  9764.74447753,
        9804.31162059,  9853.14223038,  9850.56147198,  9684.2613353 ,
        9673.36983564,  9621.86011642,  9683.9264325 ,  9781.91250933,
        9717.55231377,  9763.06789394,  9932.54293905,  9866.22208637,
       10032.16422056,  9946.63140825,  9948.91513051,  9947.80626305,
        9948.95015133,  9865.60998051,  9807.28616123,  9741.80092199,
        9773.65296712,  9805.90945388, 10024.18353955, 10161.61399384,
       10109.8056916 , 10142.64937851, 10243.78355919, 10246.91834384,
      

## 정수 데이터 카운팅
* 만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석

### `unique`
* unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
* return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력


In [ ]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [ ]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [ ]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
count

array([2, 2, 1])

### `bincount`
* `unique` 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않음
* 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 `bincount` 함수에 `minlength` 인수를 설정하여 쓰는 것이 더 편리
* `bincount` 함수는 0 부터 `minlength` - 1 까지의 숫자에 대해 각각 카운트
* 데이터가 없을 경우에는 카운트 값이 0이 됨

In [ ]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0])