<a href="https://colab.research.google.com/github/jaiwon880/DataAnalysis_23/blob/main/jaiwon880/ch05_02%2B03%2B04_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)

np.concatenate([arr1, arr2], axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate([arr1, arr2, arr1, arr2])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = arr1.reshape(3, 1)
arr2 = arr2.reshape(3, 1)

np.concatenate([arr1, arr2])
np.concatenate([arr1, arr2], axis=1) # 열의 개수를 늘림

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a1 = np.ones((2,3))
a2 = np.zeros((2,2))

np.hstack((a1, a2))  # 행의 길이가 같아야 하고 열의 길이를 확장함!

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [ ]:
b1 = np.ones_like(a1)
b2 = np.zeros((3, 3))

np.vstack((b1, b2))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c1 = np.ones((3,4))
c2 = np.zeros_like(c1)

np.dstack((c1,c2)) # 크기가 같아야함! 가장 마지막, 안쪽의 차원이 1증가 하면서 합쳐진다

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [ ]:
c = np.stack([c1,c2],axis=0) # 행을 기준
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
c = np.stack([c1,c2],axis=1) # 열 기준
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [ ]:
c = np.stack([c1,c2],axis=-1) # 차원을 추가하면서 합쳐짐
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [ ]:
# r_ -> hstack 1, 2, 3 / 4, 5, 6 # 리스트로 안 묶어줘도 됨
d= np.r_[np.arange(1,4), np.arange(4,7), np.arange(4,9)]
d, d.ndim, d.shape


(array([1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8]), 1, (11,))

In [ ]:
# c_
d1= np.c_[np.arange(1,4), np.arange(4,7)]
d1

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.concatenate((np.arange(1,4)[:, np.newaxis], np.arange(4,7)[:, np.newaxis]), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a = np.arange(6).reshape(3, -1)
print(np.tile(a, 3)) # 모양을 지키면서 반복
print(np.repeat(a,3)) # flatten 시킨 다음에 각 원소들을 그 위치에 반복

[[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [4 5 4 5 4 5]]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [ ]:
arr = np.arange(7) # 1,2,3,4,5,6
arr

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
np.array_split(arr, 3)

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
np.split(arr,3) # array_split-> 되는대로 3등분, split은 약수에 맞게 떨어져야 쪼개줌

ValueError: ignored

In [ ]:
arr = np.arange(1, 19).reshape(-1, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.array_split(arr,3) # axis = 0 디폴트 값 

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]), array([[13, 14, 15],
        [16, 17, 18]])]

In [ ]:
np.array_split(arr,3, axis=1) # axis = 0 디폴트 값 

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [ ]:
# 브로드 캐스팅: 크기가 작은 배열을 자동으로 반복확장하여 크기가 큰 배열에 맞추는 방법
x = np.arange(5)
x + 1

array([1, 2, 3, 4, 5])

In [ ]:
x + np.ones_like(x) * 1

array([1, 2, 3, 4, 5])

In [ ]:
x + 10 # 먼저 이 과정을 거치고 더함(np.ones_like(x) * 10 )

array([10, 11, 12, 13, 14])

In [ ]:
x + np.full_like(x ,10)

array([10, 11, 12, 13, 14])

In [ ]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
y = np.arange(5).reshape(-1,1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [ ]:
np.repeat(y, 2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
x = np.arange(1,5) # 1 ~ 4

In [ ]:
np.sum(x), x.sum()

(10, 10)

In [ ]:
x.min(), x.max()

(1, 4)

In [ ]:
x.argmin(), x.argmax()

(0, 3)

In [ ]:
x.mean() # np.mean

2.5

In [ ]:
np.median(x)

2.5

In [ ]:
np.any(x > 4)

False

In [ ]:
np.any(x > 2)

True

In [ ]:
np.all(x > 2), np.all(x >= 0)

(False, True)

In [ ]:
x = np.array(((1,1),(2,2)))
x

array([[1, 1],
       [2, 2]])

In [ ]:
x.sum()

6

In [ ]:
x.sum(axis=0) # 행내부에 있는 열들 간의 연산

array([3, 3])

In [ ]:
x.sum(axis=1) # 열내부에 있는 행들 간의 연산

array([2, 4])

In [ ]:
a = np.random.randint(1, 20, size=12).reshape(3,-1)
a

array([[ 7, 16,  6,  1],
       [ 8, 12,  9, 12],
       [19, 17, 17, 17]])

In [ ]:
np.sort(a) # 행을 그대로, 열들 간의 정리 axis=0
np.sort(a, axis=1)

array([[ 1,  6,  7, 16],
       [ 8,  9, 12, 12],
       [17, 17, 17, 19]])

In [ ]:
np.sort(a, axis=0) # 열을 그대로, 행들 간의 정리 axis=0

array([[ 7, 12,  6,  1],
       [ 8, 16,  9, 12],
       [19, 17, 17, 17]])

In [ ]:
a.sort(axis=1) # in-place 사본을 만드는 게 아니라 원본에 영향을 끼침

In [ ]:
np.argsort(a)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.argsort(a, axis=0)

array([[0, 0, 0, 1],
       [1, 1, 1, 0],
       [2, 2, 2, 2]])

In [ ]:
x = np.random.randint(0, 100, 12).reshape(3, -1)
x

array([[27, 97, 97, 78],
       [38, 31,  8, 50],
       [69, 36, 37,  8]])

In [ ]:
x[:, np.argsort(x[1])] # 두 번쨰 행을 기준으로!

array([[97, 97, 27, 78],
       [ 8, 31, 38, 50],
       [37, 36, 69,  8]])

In [ ]:
x = np.random.randint(-30, 30, 30)
x

array([-18,   8,   3,  26, -24,  -3,  -7,   9,  11,   4, -15,   8, -13,
        16, -15,  22,  -9, -25, -30,   2,   6, -19,  -5,  -8,  -8,  29,
       -28, -14,  -3,  -3])

In [ ]:
len(x)

30

In [ ]:
np.mean(x), x.mean()

(-3.433333333333333, -3.433333333333333)

In [ ]:
np.var(x), x.var()

(233.11222222222221, 233.11222222222221)

In [ ]:
np.std(x), x.std()

(15.26801304106799, 15.26801304106799)

In [ ]:
np.max(x), np.min(x)

(29, -30)

In [ ]:
np.median(x) # 짝수개일 경우, 두값의 평균

-4.0

In [ ]:
np.quantile(x, 0), np.quantile(x, 1)

(-30, 29)

In [ ]:
np.quantile(x, 0.25), np.percentile(x, 25),np.quantile(x, 1/4)

(-14.75, -14.75, -14.75)

In [ ]:
np.quantile(x, 0.5), np.percentile(x, 50), np.quantile(x, 2/4)

(-4.0, -4.0, -4.0)

In [ ]:
np.quantile(x, 0.75), np.percentile(x, 75),np.quantile(x, 3/4) 

(7.5, 7.5, 7.5)

In [ ]:
np.random.seed(0) # 이후에 나오는 랜덤값들이 순서가 일치

In [ ]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(x)

In [ ]:
x

array([3, 1, 8, 7, 9, 0, 6, 4, 2, 5])

In [ ]:
np.random.choice(x,5, replace=False)

array([6, 9, 2, 0, 4])

In [ ]:
np.random.choice(5, 5, replace=False)

array([4, 2, 3, 1, 0])

In [ ]:
np.random.choice(np.arange(1,46), 6 replace=False))

array([ 2, 37, 11, 23, 44, 41])

In [ ]:
np.random.choice(np.arange(1,46), 6, replace=True)

array([15, 16, 21, 36, 24, 16])

In [ ]:
np.random.choice(np.arange(1,7), 6, p=[0,0,0,0.6,0.2,0.2])

array([5, 4, 5, 4, 4, 4])

In [ ]:
np.random.randn(10) # 0 평균, 표준편차 -1, -2, +2 => 99.9%에 가까울수록 값들이 더 많이 등장

array([ 0.90751962, -0.58582287,  0.93755884, -0.25460809,  0.97359871,
        0.20728277,  1.09964197,  0.93989698,  0.606389  ,  0.00176084])

In [ ]:
np.random.randn(3,5)

array([[-0.99016014,  1.87239408, -0.24107359,  0.05334491,  1.03081595],
       [-1.27698899,  0.83771977, -1.49011141, -1.070215  , -0.20912862],
       [ 0.60457228, -1.74305823,  1.52422681,  1.86357532,  1.29137792]])

In [ ]:
np.random.randint(10) # 최소 0 , low

3

In [ ]:
np.random.randint(1, 10) # 최소 low, 최대 high

3

In [ ]:
np.random.randint(1, 10, 100) # 최소 low, 최대 high, size = 100 입력해도 됨

array([4, 7, 4, 7, 6, 8, 1, 9, 5, 7, 6, 9, 3, 4, 8, 6, 4, 5, 6, 4, 4, 8,
       8, 4, 3, 4, 8, 8, 6, 2, 3, 3, 9, 2, 6, 9, 5, 1, 3, 6, 6, 1, 9, 2,
       2, 1, 4, 9, 9, 5, 5, 1, 4, 8, 4, 3, 2, 2, 3, 2, 5, 3, 6, 6, 6, 3,
       6, 8, 8, 7, 2, 7, 8, 3, 4, 2, 6, 3, 1, 2, 1, 7, 1, 5, 9, 5, 4, 4,
       9, 9, 8, 1, 4, 9, 8, 8, 2, 9, 5, 8])

In [ ]:
# 가격이 10,000원인 주식이 있다. 
price = 10000
# 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다
days = 250
daily_earning_rate = np.random.randn(days) / 100 # 기댓값이 0
print(daily_earning_rate)
# 250일 동안의 주가를 무작위로 생성하라
# 주가 -> 전일 가격 * (1 + 당일 수익률)
price_arr = np.empty(days)
for i, v in enumerate(daily_earning_rate):
  print(v)
  price *= (1 + v)
  price_arr[i] = price
  print(price_arr[i])
  print(price)
price_arr

[-0.00912783  0.0021951   0.00393063 -0.00938982  0.01017021  0.01422983
  0.00396087 -0.00591403  0.01124419  0.00755396  0.00867407 -0.00656464
 -0.02834555  0.02116791 -0.01610878 -0.00035768  0.02380745  0.00330577
  0.00949246 -0.01502397 -0.01777667 -0.00532703  0.0109075  -0.00346249
 -0.00794636  0.00197967  0.01081935 -0.0144494  -0.01210543 -0.00788669
  0.01094638  0.00234822  0.02132153  0.00936446 -0.00035095  0.01265078
  0.00211497 -0.00704921  0.00679975 -0.00696327 -0.00290397  0.01327783
 -0.00101281 -0.00803141 -0.00464338  0.01021791 -0.00552541 -0.00386871
 -0.00510293  0.00183925 -0.0038549  -0.01601836 -0.00887181 -0.00932789
  0.01243319  0.00812674  0.00587259 -0.00505358 -0.00815792 -0.00507518
 -0.0105188   0.024972   -0.02245322  0.00564009 -0.01284552 -0.00104343
 -0.00988002 -0.01177629 -0.01140196  0.01754986 -0.00132988 -0.00765702
  0.00555787  0.00010349  0.00720034 -0.01824257  0.00303604  0.00772695
 -0.01661598  0.00448195  0.01696182 -0.00014858  0

array([ 9908.72165059,  9930.47224147,  9969.50524702,  9875.89342986,
        9976.33333913, 10118.2949161 , 10158.37212489, 10098.29524114,
       10211.84241014, 10288.98222816, 10378.22962256, 10310.10031498,
       10017.854902  , 10229.91195511, 10065.12051274, 10061.5204132 ,
       10301.0595927 , 10335.11250136, 10433.21819232, 10276.46988012,
       10093.78847095, 10040.01857795, 10149.53005392, 10114.38736217,
       10034.01476654, 10053.87883364, 10162.65528957, 10015.810998  ,
        9894.56529966,  9816.52990527,  9923.98540868,  9947.28906265,
       10159.38052566, 10254.51761036, 10250.91876927, 10380.60087082,
       10402.55553157, 10329.22569642, 10399.46183276, 10327.04760816,
       10297.05816131, 10433.78071776, 10423.21322958, 10339.50009025,
       10291.48989422, 10396.64736908, 10339.20166369, 10299.20230666,
       10246.64622505, 10265.49241977, 10225.91999764, 10062.11752478,
        9972.84833575,  9879.82269935, 10002.66045012, 10083.94947512,
      

In [ ]:
x = np.random.randint(1, 10, 100)
x

array([3, 2, 3, 6, 9, 9, 9, 3, 3, 9, 5, 2, 2, 1, 3, 2, 8, 1, 3, 4, 5, 4,
       1, 1, 7, 5, 4, 4, 2, 1, 8, 9, 7, 3, 9, 9, 7, 5, 2, 9, 6, 5, 4, 6,
       8, 7, 7, 4, 4, 3, 8, 4, 6, 9, 4, 9, 6, 1, 8, 1, 2, 7, 7, 5, 6, 8,
       7, 1, 2, 7, 7, 5, 3, 3, 5, 5, 4, 2, 1, 7, 7, 1, 9, 6, 3, 9, 5, 5,
       1, 3, 6, 8, 8, 2, 4, 3, 1, 4, 3, 3])

In [ ]:
np.unique(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.unique(x, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([12, 10, 15, 12, 11,  8, 12,  8, 12]))

In [ ]:
np.unique(x, return_counts=True, return_index=True) # 순서 뒤집기

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([13,  1,  0, 19, 10,  3, 24, 16,  4]),
 array([12, 10, 15, 12, 11,  8, 12,  8, 12]))

In [ ]:
np.unique(x, return_index=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([13,  1,  0, 19, 10,  3, 24, 16,  4]))

In [ ]:
key, value = np.unique(x, return_counts=True)
print(key)
print(value)

[1 2 3 4 5 6 7 8 9]
[12 10 15 12 11  8 12  8 12]


In [ ]:
# 2개의 시퀀스를 인덱스로 묶어줌 -> zip
list(zip(key, value))

[(1, 12), (2, 10), (3, 15), (4, 12), (5, 11), (6, 8), (7, 12), (8, 8), (9, 12)]

In [ ]:
dict(list(zip(key, value)))

{1: 12, 2: 10, 3: 15, 4: 12, 5: 11, 6: 8, 7: 12, 8: 8, 9: 12}

In [ ]:
dict(zip(key, value))

{1: 12, 2: 10, 3: 15, 4: 12, 5: 11, 6: 8, 7: 12, 8: 8, 9: 12}

In [ ]:
dict(zip(*np.unique(x, return_counts=True)))

{1: 12, 2: 10, 3: 15, 4: 12, 5: 11, 6: 8, 7: 12, 8: 8, 9: 12}

In [ ]:
x = np.random.randint(30, size= 10)
x

array([29, 10, 18, 28,  3, 21, 26, 17,  7, 10])

In [ ]:
dict(zip(*np.unique(x, return_counts=True))) # 뽑히지 않은 것에 대해서

{3: 1, 7: 1, 10: 2, 17: 1, 18: 1, 21: 1, 26: 1, 28: 1, 29: 1}

In [ ]:
np.bincount(x, minlength=30)

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1])

In [ ]:
np.arange(30), np.bincount(x, minlength=30)


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 1, 1]))

In [ ]:
dict(zip(np.arange(30), np.bincount(x, minlength=30)))

{0: 0,
 1: 0,
 2: 0,
 3: 1,
 4: 0,
 5: 0,
 6: 0,
 7: 1,
 8: 0,
 9: 0,
 10: 2,
 11: 0,
 12: 0,
 13: 0,
 14: 0,
 15: 0,
 16: 0,
 17: 1,
 18: 1,
 19: 0,
 20: 0,
 21: 1,
 22: 0,
 23: 0,
 24: 0,
 25: 0,
 26: 1,
 27: 0,
 28: 1,
 29: 1}