<a href="https://colab.research.google.com/github/andy9806/DataAnalysis_23/blob/main/andy9806/0309.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
a = np.array([1,2.0,'3'])
a

array(['1', '2.0', '3'], dtype='<U32')

In [10]:
a=np.array([[[1,2,3],
             [4,5,6]],
            [[7,8,9],
             [10,11,12]]])
print(a.shape)
a.T.shape

(2, 2, 3)


(3, 2, 2)

In [11]:
print(a)
print(a.T)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [12]:
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)
arr1 + arr2

array([5, 7, 9])

In [18]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [28]:
arr1 = arr1.reshape(3,1)
arr2 = arr2.reshape(3,1)
print(arr1)
print(arr2)

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]


In [29]:
np.hstack((arr1,arr2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
np.concatenate((arr1,arr2),axis=1)  #axis=1 열방향

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
np.concatenate((arr1,arr2))  #axis=0 행방향

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [34]:
a1 = np.ones((2,3))
a2 = np.zeros((2,2))

In [52]:
np.concatenate((a1,a2),axis=1)

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [39]:
np.hstack((a1,a2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [40]:
np.column_stack((a1,a2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [43]:
b1 = np.ones((2,3))
b2 = np.zeros((4,3))

In [44]:
np.vstack((b1,b2))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.concatenate((b1,b2))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))

In [56]:
print(c1)
print(c2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [57]:
np.dstack((c1,c2))

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [60]:
print(np.full((4,4),i) for i in range(10))

<generator object <genexpr> at 0x7f5c3cfd2040>


In [89]:
a = np.zeros(3,dtype='f')
# a = np.full((1,3),0,dtype='f')
# a = np.repeat(np.zeros(1,dtype='f'),3)
# a = np.tile(np.zeros(1,dtype='f'),3)
a

array([[0., 0., 0.]], dtype=float32)

In [67]:
b = np.ones(2,dtype='f')
b

array([1., 1.], dtype=float32)

In [70]:
c = np.concatenate((a,b))
# c = np.hstack((a,b))
c

array([0., 0., 0., 1., 1.], dtype=float32)

In [74]:
d = np.tile(c,(3,1))
d

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]], dtype=float32)

In [77]:
e = np.arange(1,16,dtype='f')*10
e

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.,
       120., 130., 140., 150.], dtype=float32)

In [78]:
f = e.reshape(3,5)
f

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]], dtype=float32)

In [80]:
g = np.concatenate((d,f))
# g = np.vstack((d,f))
g

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]], dtype=float32)

In [81]:
np.tile(g,(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]], dtype=float32)

In [83]:
np.full((2,4),1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [90]:
arr = np.arange(1,7)
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [96]:
arr1 = np.arange(1,19).reshape(-1,3)
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [100]:
np.array_split(arr1,3,axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [102]:
x=np.arange(1,10001)
y=np.arange(10001,20001)

In [103]:
z=x+y
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [104]:
a=np.arange(1,5)
b = np.array([4,2,2,4])
c=np.arange(1,5)

In [106]:
a==b

array([False,  True, False,  True])

In [107]:
np.all(a==b)

# 완전히 동일한지 확인

False

In [108]:
np.all(a==c)

True

In [109]:
np.any(a==b)
# 하나라도 성립하는지

True

In [110]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [111]:
y = np.arange(5)[:,np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [112]:
x+y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [122]:
a = np.array([1,4,5,2,3,4,5,6,7,8,2,3,1,10,12,11])
a

array([ 1,  4,  5,  2,  3,  4,  5,  6,  7,  8,  2,  3,  1, 10, 12, 11])

In [123]:
a.min() , a.max()

(1, 12)

In [124]:
a.argmin() , a.argmax()

(0, 14)

In [128]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [129]:
a.sum(axis=0)

array([4, 6])

In [131]:
a.sum(axis=1)

array([3, 7])

In [132]:
x = np.arange(30).reshape((5,6))
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [133]:
x.max()

29

In [134]:
for i in x:
  print(i.max())

5
11
17
23
29


In [135]:
for i in x.T:
  print(i.mean())

12.0
13.0
14.0
15.0
16.0
17.0


In [136]:
for i in x.T:
  print(i.min())

0
1
2
3
4
5


In [142]:
x.sum(axis=1)

array([ 15,  51,  87, 123, 159])

In [143]:
x.max(axis=1)

array([ 5, 11, 17, 23, 29])

In [144]:
x.max(axis=0)

array([24, 25, 26, 27, 28, 29])

In [145]:
x.mean(axis=0)

array([12., 13., 14., 15., 16., 17.])

In [146]:
x.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5, 26.5])

In [147]:
a = np.array([[4,5,5,7],
             [1,12,11,9],
             [2,15,1,14],
             ])
a

array([[ 4,  5,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [148]:
np.sort(a)

array([[ 4,  5,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [149]:
np.sort(a,axis=0)

array([[ 1,  5,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [150]:
np.sort(a,axis=1)

array([[ 4,  5,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [151]:
np.sort(a,axis=-1)

array([[ 4,  5,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [158]:
a.sort(axis=1)  #a.sort()는 원본에 영향
a

array([[ 1,  2,  5,  7],
       [ 1,  5, 11, 12],
       [ 4,  9, 14, 15]])

In [159]:
a = np.array([42,38,12,25])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [160]:
c = np.array([[1,2,3,4],
              [46,99,100,71],
              [81,59,90,100]]
             )
c

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [163]:
np.argsort(c[1,:])

array([0, 3, 1, 2])

In [164]:
c[:,np.argsort(c[1,:])]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [168]:
np.random.choice(10,2,replace=True)  #0 에서9 중에 2개를 복원추출 replace=True는 복원

array([8, 3])

In [171]:
np.random.choice(5,10)

array([3, 3, 0, 2, 4, 4, 3, 4, 1, 4])

In [176]:
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0])  #p로 확률 설정 가능

array([3, 0, 3, 0, 3, 3, 3, 3, 3, 3])