<a href="https://colab.research.google.com/github/Yeaaaaaaah/DataAnalysis/blob/main/Yeaaaaaaah/ch05_03_%EB%B0%B0%EC%97%B4%EC%9D%98_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 배열의 연산

## 벡터화 연산 (vectorized operation)
* 명시적으로 반복문을 사용하지 않고도 배열의 모든 원소에 대해 반복 연산을 할 수 있음
* 선형 대수 공식과 동일한 아주 간단한 파이썬 코드를 작성할 수 있음

<br>
$$
x = \begin{bmatrix}1\\2\\3\\⋯\\10000\end{bmatrix},\quad
y = \begin{bmatrix}10001\\10002\\10003\\⋯\\20000\end{bmatrix}
$$

<br>
$$
z = x + y
$$

<br>
$$
\begin{bmatrix}1\\2\\3\\⋯\\10000\end{bmatrix}
+ \begin{bmatrix}10001\\10002\\10003\\⋯\\20000\end{bmatrix}
= \begin{bmatrix}1+10001\\2+10002\\3+10003\\⋯\\10000+20000\end{bmatrix}
= \begin{bmatrix}10002\\10004\\10006\\⋯\\30000\end{bmatrix}
$$



In [6]:
import numpy as np

# x = np.array(range(1, 10001))
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

x
y

array([10001, 10002, 10003, ..., 19998, 19999, 20000])

In [11]:
%%time
z = np.zeros_like(x)
for i in range(len(z)):
  z[i] = x[i] + y[i]
  

CPU times: user 9.13 ms, sys: 0 ns, total: 9.13 ms
Wall time: 12.7 ms


In [12]:
%%timeit
z = np.zeros_like(x)
for i in range(len(z)):
  z[i] = x[i] + y[i]
  

5.03 ms ± 1.97 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
%%time
z = x + y

CPU times: user 1.18 ms, sys: 12 µs, total: 1.19 ms
Wall time: 1.29 ms


In [15]:
%%timeit
z = x + y

6.76 µs ± 1.65 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# 사칙 연산뿐 아니라 비교 연산과 같은 논리 연산도 벡터화 연산이 가능


In [18]:
x == y

array([False, False, False, ..., False, False, False])

In [19]:
(x == y) | (x > y)

array([False, False, False, ..., False, False, False])

In [20]:
# 배열의 각 원소를 일일히 비교하는 것이 아닌 배열의 모든 원소가 다 같은지 알고 싶다면 all 명령 사용
a = np.arange(1,5)
b = np.array((4,2,2,4))
c = np.arange(1,5)

In [21]:
print(a)
print(b)
a == b

[1 2 3 4]
[4 2 2 4]


array([False,  True, False,  True])

In [23]:
np.all( a == b)

False

In [26]:
print(a)
print(c)
np.all(a == c)

[1 2 3 4]
[1 2 3 4]


True

In [27]:
# any : 하나라도 성립하는지
print(a)
print(b)
np.any(a==b)

[1 2 3 4]
[4 2 2 4]


True

In [28]:
# 지수 함수, 로그 함수 등의 수학 함수도 벡터화 연산을 지원
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
np.ex

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

array([    1,    10,   100,  1000, 10000])

In [29]:
np.log(a+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

## 스칼라와 벡터/행렬의 곱셈

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [32]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
100 * x 

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅
* 벡터(또는 행렬)끼리 덧셈 혹은 뺄셈을 하려면 두 벡터(또는 행렬)의 크기가 같아야 함
* Numpy에선 서로 다른 크기를 가진 두 배열의 사칙 연산 지원 = 브로드캐스팅(broadcasting)
> 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방법

<br>
$$
x = \begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix},\quad 
x + 1 = \begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix} + 1 = ?
$$
<br>
$$
\begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix} + 1
= \begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix}
+ \begin{bmatrix}1\\1\\1\\1\\1\end{bmatrix}
= \begin{bmatrix}1\\2\\3\\4\\5\end{bmatrix}
$$

In [34]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [35]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [36]:
x + y

array([1, 2, 3, 4, 5])

In [38]:
x + 1

array([1, 2, 3, 4, 5])

In [39]:
# x + 2
y = np.full_like(x, 2)
x + y

array([2, 3, 4, 5, 6])

In [41]:
# 2차원 이상에서도 적용됨
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x, x.ndim, x.shape

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [43]:
y = np.arange(5)[:,np.newaxis]
y, y.ndim, y.shape

(array([[0],
        [1],
        [2],
        [3],
        [4]]), 2, (5, 1))

In [45]:
z = x + y
z, z.ndim, z.shape

(array([[ 0,  1,  2],
        [ 2,  3,  4],
        [ 4,  5,  6],
        [ 6,  7,  8],
        [ 8,  9, 10]]), 2, (5, 3))

In [46]:
y = np.arange(3)
y, y.ndim, y.shape 

(array([0, 1, 2]), 1, (3,))

In [47]:
z = x + y
z, z.ndim, z.shape #단 여기서 x와 y는 배수 관계여야한다.

(array([[0, 2, 4],
        [1, 3, 5],
        [2, 4, 6],
        [3, 5, 7],
        [4, 6, 8]]), 2, (5, 3))

## 차원 축소 연산 (dimension reduction)
> 행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 각 행에 처리된 연산으로 한 차원 낮은 벡터를 구성하게 하는 연산
* 최대/최소 : `min`, `max`, `argmin`, `argmax`
* 통계 : `sum`, `mean`, `median`, `std`, `var`
* 불리언 : `all`, `any`

In [49]:
x = np.arange(1,5)
x

array([1, 2, 3, 4])

In [52]:
np.sum(x), x.sum()

(10, 10)

In [53]:
x = np.array([1,3,2])

In [54]:
x.min(), x.max(),

(1, 3)

In [55]:
x.argmin() #최솟값의 위치

0

In [56]:
x.argmax() # 최댓값의 위치

1

In [57]:
x = np.array([1,2,3,1])

In [59]:
x.mean(), x.sum()/len(x)

(1.75, 1.75)

In [61]:
np.median(x) # 1, 1, 2, 3

1.5

In [64]:
a = np.zeros((100,100), dtype='f')
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [65]:
np.any(a !=0)

False

In [66]:
np.all(a == a)

True

In [67]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

In [70]:
((a <= b) & (b <= c)).all()

True

In [71]:
((a <= b) & (b <= c)).all()

True

* 연산의 대상이 2차원 이상인 경우에는 어느 차원으로 계산을 할 지를 axis 인수를 사용하여 지시
* axis=0인 경우는 열 연산, axis=1인 경우는 행 연산. 디폴트 값은 axis=0.
* axis 인수는 대부분의 차원 축소 명령에 적용할 수 있음

In [72]:
x = np.array(((1,1), (2,2)))
x

array([[1, 1],
       [2, 2]])

In [73]:
x.sum()

6

In [74]:
x.sum(axis=0) # 열 합계 (열 연산)

array([3, 3])

In [75]:
x.sum(axis=1) # 행 합계 (행 연산)

array([2, 4])

## 💡 연습문제 5
실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값 도출
1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값

In [77]:
a = np.arange(30, dtype='f').reshape((5,6))
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.]], dtype=float32)

In [81]:
# 전체의 최댓값
a.max()

29.0

In [84]:
# 각 행의 합
a.sum(axis=1)

array([ 15.,  51.,  87., 123., 159.], dtype=float32)

In [85]:
# 각 행의 최댓값
a.max(axis=1)

array([ 5., 11., 17., 23., 29.], dtype=float32)

In [87]:
# 각 열의 평균
a.mean(axis=0)

array([12., 13., 14., 15., 16., 17.], dtype=float32)

In [88]:
# 각 열의 최솟값
a.min(axis=0)

array([0., 1., 2., 3., 4., 5.], dtype=float32)

## 정렬
* `sort` : 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열 생성
* 2차원 이상인 경우에는 행이나 열을 각각 따로따로 정렬
    * `axis=0` : 각각의 행을 따로따로 정렬
    * `axis=1` : 각각의 열을 따로따로 정렬 
    * `axis=-1` : 가장 안쪽(나중)의 차원 (default)

In [89]:
a = np.array(
    [[4, 3, 5, 7],
    [1, 12, 11, 9],
    [2, 15, 1, 14]]
)
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [91]:
np.sort(a) # axis =-1 이 디폴트 (가장 안쪽 차원의 열들간의 정렬)
np.sort(a, axis=1)
np.sort(a, axis= -1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [92]:
np.sort(a, axis = 0) # 행들간의 정렬 #원본 영향x

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [93]:
# sort 메서드는 해당 객체의 자료 자체가 변화하므로 주의
# 자체변화(in-place) 메서드 = 원본이 수정됨
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

* `argsort` : 자료 정렬이 아니라 순서만 알고 싶다면 사용

In [94]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [95]:
a[j]

array([12, 25, 38, 42])

In [96]:
np.sort(a)

array([12, 25, 38, 42])

## 💡 연습문제 6
> 두 번째 행을 기준으로 각 열(column)을 재정렬
```
array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
```

In [112]:
x = np.array([
    [1, 2, 3, 4],
    [46, 99, 100, 71],
    [81, 59, 90, 100]
])
x

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [114]:
x[:]

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [117]:
# np.sort(x[1])
np.argsort(x[1])

array([0, 3, 1, 2])

In [118]:
x[:,np.argsort(x[1])]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])