<a href="https://colab.research.google.com/github/CHOISEONGGU/DataAnalysis_ChoiSG/blob/main/CHOISEONGGU/%EB%B3%B5%EC%8A%B5/ch05_01%2B02_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#!pip install numpy
import numpy as np   # 이 줄은 규칙

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array((1, 2, 3))

array([1, 2, 3])

In [4]:
np.array(range(1, 4))

array([1, 2, 3])

In [9]:
np.array([int(c) for c in "123"])

array([1, 2, 3])

In [10]:
arr = np.array([1, 2, 3])

In [11]:
type(arr)   # n-dimentional array

numpy.ndarray

In [12]:
%time arr   # 시간 체크

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 9.3 µs


array([1, 2, 3])

## 벡터화 연산

In [14]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
a + 10

TypeError: ignored

In [17]:
a + [10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
a * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
b = [i * 2 for i in a]   # list comprehension 표현법
b

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [22]:
arr = np.arange(10)   # np.array(range(10)) 과 같은 코드
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr + 2   # 배열(np.ndarray)에서 산술 연산자는 각각의 원소들에 대해서 계산 진행

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
np.ones_like(arr) * 2   # 이런 배열을 추가로 만들어서 더해주는 얘기가 더 맞다.

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [28]:
arr + np.ones_like(arr) * 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [30]:
(((arr * 5 ) // 2 ) -1 ) % 7   # 복잡한 계산도 가능하다.

array([6, 1, 4, 6, 2, 4, 0, 2, 5, 0])

In [33]:
arr == 5   # 각각 다 비교, (bool 인덱싱)

array([False, False, False, False, False,  True, False, False, False,
       False])

In [34]:
arr[arr == 5]

array([5])

In [36]:
arr[arr > 5]

array([6, 7, 8, 9])

In [42]:
np.where(arr > 5)

(array([6, 7, 8, 9]),)

In [43]:
arr2 = np.arange(6, 25, 2)
arr2

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [44]:
np.where(arr2 % 3 == 0)   # index로 표현돼서 나온다.

(array([0, 3, 6, 9]),)

In [45]:
arr2[np.where(arr2 % 3 == 0)]   # arr2[arr2 % 3 == 0] 과 같은 내용

array([ 6, 12, 18, 24])

In [50]:
arr[(arr > 5) | (arr % 2 == 0)]

array([0, 2, 4, 6, 7, 8, 9])

In [51]:
arr[(arr > 5) & (arr % 2 == 0)]

array([6, 8])

In [53]:
# n-dimensional array
np.array([[1, 2, 3, 4], [1, 2, 3, 4]])   # 행들 간의 길이( 열의 크기가 ) 같아야 함.

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [55]:
np.array([[1, 2, 3, 4], [1, 2, 3]])

<ipython-input-55-e6426570ace6>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, 2, 3, 4], [1, 2, 3]])


array([list([1, 2, 3, 4]), list([1, 2, 3])], dtype=object)

In [56]:
a1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [58]:
a1[1, 1]

2

In [60]:
a2 = np.array([[1, 2, 3, 4], [1, 2, 3]])
a2[1, 1]

<ipython-input-60-b813f9fe8871>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = np.array([[1, 2, 3, 4], [1, 2, 3]])


IndexError: ignored

In [61]:
a1.ndim, a1.shape

(2, (2, 4))

In [62]:
a2.ndim, a2.shape

(1, (2,))

In [66]:
m = np.array([[1, 2],[3, 4]])
m2 = np.array((range(2, 4), range(5, 7)))
print(m)
print(m2)

[[1 2]
 [3 4]]
[[2 3]
 [5 6]]


In [69]:
t = np.array([
    [
        [1, 3, 5, 2],
        [1, 3, 5, 2],
        [1, 3, 5, 2]
    ],
    [
        [1, 3, 5, 2],
        [1, 3, 5, 2],
        [1, 3, 5, 2]
    ],
])
t

array([[[1, 3, 5, 2],
        [1, 3, 5, 2],
        [1, 3, 5, 2]],

       [[1, 3, 5, 2],
        [1, 3, 5, 2],
        [1, 3, 5, 2]]])

In [70]:
t.ndim, t.shape

(3, (2, 3, 4))

In [71]:
a = np.arange(10).reshape(2, 4)   # 10 이 나와야하는데 8이 나왔음
# shape에 들어가는 매개변수들은, 모두 곱했을 때 전체 원소 크기가 ..

ValueError: ignored

In [72]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [73]:
b = a
b[0,1] = 9

In [74]:
print(a)
print(b)

[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [77]:
c = a.copy()
c[2, 1] = -99
print(a)
print(c)

[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[  0   9]
 [  2   3]
 [  4 -99]
 [  6   7]
 [  8   9]]


### indexing

In [78]:
a = np.arange(1, 100, 25)
a


array([ 1, 26, 51, 76])

In [82]:
a[3], a[-1], a[a.shape[0]-1]

(76, 76, 76)

In [83]:
# axise (축)
# , (comma) 로 표시
m = np.arange(6).reshape((2, 3))   # reshape tuple 값으로 할당
m

array([[0, 1, 2],
       [3, 4, 5]])

In [86]:
m[0, 0], m[0, 1]

(0, 1)

In [87]:
m.ndim, m.shape

(2, (2, 3))

In [89]:
m[m.shape[0]-2, 0], m[-2, -1]

(0, 2)

In [92]:
d1, d2 = m.shape   # d1 : 행 차원의 길이, d2 : 열 차원의 길이

In [93]:
m[d1-2, 0], m[d1-2, d2-1]

(0, 2)

### 슬라이싱

In [95]:
# : 슬라이싱 표현법, 시작점 : 끝점값(미포함)
# 1차원의 배열의 슬라이싱 = 리스트의 슬라이싱과 같다
a[1:3]

array([26, 51])

In [96]:
a2 = np.arange(1, 100, 10)
a2

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [98]:
a2[1:10:2], a2[10::-1]

(array([11, 31, 51, 71, 91]), array([91, 81, 71, 61, 51, 41, 31, 21, 11,  1]))

In [99]:
m

array([[0, 1, 2],
       [3, 4, 5]])

In [102]:
m[0,:], m[0]

(array([0, 1, 2]), array([0, 1, 2]))

In [104]:
m[:0]
print(m[:, 0:1])

[[0]
 [3]]


## 배열의 자료형

In [105]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [107]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [108]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [109]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [110]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [111]:
np.ones_like(a)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [120]:
np.empty((2, 5))

array([[3.29806368e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 5.28558918e+180],
       [3.14138844e+179, 3.27043307e+179, 5.64042854e-091,
        5.88364745e-062, 2.66532324e-260]])

In [121]:
np.linspace(10, 100, 5)   # y = x

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [122]:
np.logspace(0.1, 1, 5)   # y = log x

array([ 1.25892541,  2.11348904,  3.54813389,  5.95662144, 10.        ])

In [123]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
A.ndim, A.shape

(2, (2, 3))

In [125]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [127]:
A, A.flatten(), A.ravel()

(array([[1, 2, 3],
        [4, 5, 6]]), array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 4, 5, 6]))

In [129]:
t = np.arange(30).reshape(3, 5, 2)
t

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [131]:
t.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [133]:
x = np.arange(5)
print(x, x.ndim, x.shape)
x2 = x[:, np.newaxis]
print(x2, x2.ndim, x2.shape)
x3 = x[np.newaxis, :]
print(x3, x3.ndim, x3.shape)

[0 1 2 3 4] 1 (5,)
[[0]
 [1]
 [2]
 [3]
 [4]] 2 (5, 1)
[[0 1 2 3 4]] 2 (1, 5)
