<a href="https://colab.research.google.com/github/KHB2937/DataAnalysis/blob/main/kwak/%EB%B3%B5%EC%8A%B5/ch05_02%2B03%2B04_%EB%B3%B5%EC%8A%B5_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr1 = np.arange(1, 4)
arr2 = np.arange(4, 7)
np.concatenate([arr1, arr2, arr1], axis=0)

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [7]:
arr1 = arr1.reshape(3, 1)
arr2 = arr2.reshape(3, 1)
# np.concatenate([arr1, arr2, arr1], axis=0)
np.concatenate([arr1, arr2, arr1], axis=1)

array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])

In [8]:
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))
np.hstack((a1, a2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [10]:
# b1 = np.ones((2, 3))
b1 = np.ones_like(a1)
b2 = np.zeros((3, 3))
np.vstack((b1, b2))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
c1 = np.ones((3, 4))
c2 = np.zeros_like(c1)
np.dstack((c1, c2))

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [14]:
# c = stack([c1, c2])
c = np.stack([c1, c2], axis=-1)
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [13]:
np.stack([c1, c2], axis=1)#열 기준

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [16]:
np.stack([c1, c2], axis=0)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
# r_ -> hstack
np.r_[np.arange(1, 4), np.arange(4, 7)]

array([1, 2, 3, 4, 5, 6])

In [19]:
np.r_[np.arange(1, 4), np.arange(4, 7), np.arange(4, 7)]

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [24]:
np.concatenate((np.arange(1, 4)[:, np.newaxis], np.arange(4, 7)[:, np.newaxis]), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
a = np.arange(6).reshape(2, -1)
print(np.tile(a, 3))
print(np.repeat(a, (3)))

[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [29]:
arr = np.arange(7)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [30]:
np.array_split(arr, 3)

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

In [32]:
arr = np.arange(6)
np.split(arr, 3) #array_split -> 되는대로 3등분, split: 엄격하게 약수로 맞게 입력해야 쪼개줌

[array([0, 1]), array([2, 3]), array([4, 5])]

In [33]:
arr = np.arange(1, 19).reshape(-1, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [35]:
np.array_split(arr, 3, axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

## 브로드 캐스팅

In [36]:
# 브로드캐스팅 : 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방법
x = np.arange(5)
x + 1

array([1, 2, 3, 4, 5])

In [40]:
x + np.ones_like(x) * 1

array([1, 2, 3, 4, 5])

In [41]:
x + 10

array([10, 11, 12, 13, 14])

In [42]:
np.ones_like(x) * 10

array([10, 10, 10, 10, 10])

In [43]:
x+ np.full_like(x, 10)

array([10, 11, 12, 13, 14])

In [64]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [46]:
y = np.arange(5).reshape(-1, 1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [47]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [49]:
x = np.arange(1, 5)

In [50]:
np.sum(x)

10

In [51]:
x.min()

1

In [54]:
x.argmin(), x.argmax()

(0, 3)

In [55]:
x.mean()

2.5

In [58]:
np.median(x)

2.5

In [59]:
np.any(x > 4), np.any(x > 2)

(False, True)

In [60]:
np.all(x > 4), np.all(x > 2), np.all(x >= 0)

(False, False, True)

In [66]:
x.sum(axis=0) # 행 내부의 있는 열들간의 연산, 행의 대푯값(axis=0)

array([10, 15, 20])

In [65]:
x.sum(axis=1)# 열 내부의 있는 행들간의 연산, 열의 대푯값(axis=0)

array([ 3,  6,  9, 12, 15])

In [92]:
a = np.random.randint(1, 20, 12).reshape(3, -1)
a

array([[ 1,  1,  5, 15],
       [11, 11,  5, 14],
       [ 6, 17,  8,  9]])

In [95]:
np.sort(a)
np.sort(a, axis=1)# 행 정리
# a.sum(axis=0)


array([[ 1,  1,  5, 15],
       [ 5, 11, 11, 14],
       [ 6,  8,  9, 17]])

In [78]:
np.sort(a, axis=0)# 열 정리

array([[ 7,  8,  8,  1],
       [ 8, 11, 18,  2],
       [16, 18, 19,  9]])

In [81]:
np.argsort(a)

array([[0, 2, 3, 1],
       [3, 0, 1, 2],
       [3, 1, 0, 2]])

In [83]:
np.argsort(a, axis=0)

array([[0, 2, 0, 2],
       [1, 1, 2, 1],
       [2, 0, 1, 0]])

In [96]:
np.argsort(a, axis=1)

array([[0, 1, 2, 3],
       [2, 0, 1, 3],
       [0, 2, 3, 1]])

In [98]:
x = np.random.randint(1, 100, 12).reshape(3, -1)
x

array([[ 8, 62, 74, 13],
       [ 2, 76, 21, 25],
       [96, 81,  6, 94]])

In [100]:
x[:, np.argsort(x[1])]

array([[ 8, 74, 13, 62],
       [ 2, 21, 25, 76],
       [96,  6, 94, 81]])

In [103]:
x = np.random.randint(-30, 30, 30)
x

array([ 26,  -4,  -4,  14,  -9,  23,  22, -16,  14, -24, -26,  25,  25,
       -24, -26,   1, -20, -27, -18,  -1, -29,  -8, -24,  21,   8,  21,
        23,  10, -18, -23])

In [104]:
np.mean(x), x.mean()

(-2.2666666666666666, -2.2666666666666666)

In [106]:
np.var(x)

380.4622222222223

In [109]:
np.std(x), x.std()

(19.50544083639799, 19.50544083639799)

In [108]:
np.max(x), np.min(x)

(26, -29)

In [111]:
np.median(x)

-4.0

In [115]:
np.quantile(x, 0), np.percentile(x, 0)

(-29, -29.0)

In [121]:
np.quantile(x, 1/4), np.percentile(x, 25)

(-22.25, -22.25)

In [122]:
np.quantile(x, 4/4), np.percentile(x, 100)

(26.0, 26.0)

In [125]:
np.random.seed(10)

In [127]:
x = np.random.rand(5)
x

array([0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [128]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.random.shuffle(x)

In [133]:
x

array([1, 0, 8, 2, 5, 4, 9, 7, 3, 6])

In [134]:
np.random.choice(x, 5, replace=False)

array([8, 1, 6, 4, 5])

In [135]:
np.random.choice(5, 5, replace=False)

array([0, 4, 1, 2, 3])

In [136]:
np.random.choice(np.arange(1, 45), 6, replace=False)

array([ 4, 34, 39, 37, 26, 40])

In [138]:
np.random.choice(np.arange(1, 7), 6)
np.random.choice(np.arange(1, 7), 6, replace=True)


array([1, 4, 4, 2, 3, 6])

In [141]:
np.random.choice(np.arange(1, 7), 6, p=[0, 0, 0.6, 0.2, 0.2, 0])

array([3, 4, 5, 3, 4, 3])

In [142]:
np.random.randn(10)

array([-0.56543268,  0.00785023, -1.12679091,  1.513816  , -0.60729449,
        0.4183223 ,  0.98655675, -0.30135904, -0.01763348,  0.5991161 ])

In [144]:
np.random.randn(3, 5)

array([[-0.30260529, -0.74546586, -0.12852298,  1.24799151,  1.06226014],
       [-1.62863338,  0.11242771, -0.99150251,  0.67879534,  0.40970681],
       [-0.48951405, -0.00982034, -1.32018186,  0.42574122,  0.46648588]])

In [145]:
np.random.randint(1, 10)

8

In [147]:
np.random.randint(1, 10, size=100)

array([2, 7, 7, 8, 4, 1, 8, 8, 1, 3, 3, 1, 6, 9, 1, 6, 4, 7, 8, 9, 1, 7,
       1, 2, 1, 2, 5, 1, 2, 8, 4, 1, 9, 2, 6, 5, 6, 5, 4, 5, 5, 2, 2, 3,
       2, 2, 3, 3, 3, 6, 9, 2, 8, 2, 8, 2, 9, 1, 7, 8, 6, 2, 3, 7, 2, 6,
       9, 1, 4, 7, 4, 1, 3, 9, 9, 1, 8, 8, 5, 7, 4, 5, 6, 4, 6, 3, 4, 3,
       3, 6, 9, 5, 2, 7, 8, 2, 8, 2, 3, 3])

In [148]:
price = 10000

days = 250
daliy_earning_rate = np.random.randn(days) / 100

price_arr = np.empty(days)
for i, v in enumerate(daliy_earning_rate):
    price += (1+v)
    print(price)
    price_arr[i] = price
price_arr

10000.995971293483
10001.98935122846
10002.978384510352
10003.979879808889
10004.977018961017
10005.967907144664
10006.970577438755
10007.962287696655
10008.966663193616
10009.967979364343
10010.969846158609
10011.958782769003
10012.959043906316
10013.964818568002
10014.95145402124
10015.953606757335
10016.969085013428
10017.9835693349
10018.972277641478
10019.954911300349
10020.943590841043
10021.948391376021
10022.965989482276
10023.970020604113
10024.988433828226
10025.97033857575
10026.965288664305
10027.981315325189
10028.99320910397
10029.995762046887
10031.005797934333
10032.009033041633
10033.005497904986
10034.010069672235
10035.00040660589
10035.999763066726
10036.986593424672
10037.984979519539
10039.00331358106
10040.007608538535
10041.000923046817
10042.006902406429
10043.015245383496
10044.00337897129
10045.012018054562
10046.01953688386
10047.014609548725
10048.027558746513
10049.028180440624
10050.035185868655
10051.0568826298
10052.062118986789
10053.071707637304
10054

array([10000.99597129, 10001.98935123, 10002.97838451, 10003.97987981,
       10004.97701896, 10005.96790714, 10006.97057744, 10007.9622877 ,
       10008.96666319, 10009.96797936, 10010.96984616, 10011.95878277,
       10012.95904391, 10013.96481857, 10014.95145402, 10015.95360676,
       10016.96908501, 10017.98356933, 10018.97227764, 10019.9549113 ,
       10020.94359084, 10021.94839138, 10022.96598948, 10023.9700206 ,
       10024.98843383, 10025.97033858, 10026.96528866, 10027.98131533,
       10028.9932091 , 10029.99576205, 10031.00579793, 10032.00903304,
       10033.0054979 , 10034.01006967, 10035.00040661, 10035.99976307,
       10036.98659342, 10037.98497952, 10039.00331358, 10040.00760854,
       10041.00092305, 10042.00690241, 10043.01524538, 10044.00337897,
       10045.01201805, 10046.01953688, 10047.01460955, 10048.02755875,
       10049.02818044, 10050.03518587, 10051.05688263, 10052.06211899,
       10053.07170764, 10054.0615508 , 10055.06857746, 10056.07258824,
      

In [152]:
x = np.random.randint(1, 10, 1000)
x

array([9, 4, 7, 8, 8, 9, 8, 8, 4, 6, 3, 9, 8, 4, 9, 4, 6, 9, 5, 2, 7, 5,
       7, 2, 7, 8, 6, 3, 9, 1, 1, 4, 4, 2, 2, 9, 8, 5, 5, 7, 4, 1, 1, 7,
       3, 5, 3, 4, 3, 2, 2, 3, 1, 8, 8, 4, 2, 4, 4, 5, 7, 4, 4, 4, 5, 7,
       1, 9, 9, 9, 8, 8, 3, 6, 3, 9, 6, 5, 4, 4, 9, 8, 3, 9, 1, 6, 3, 6,
       5, 8, 6, 7, 2, 4, 7, 5, 2, 3, 9, 3, 5, 8, 7, 8, 7, 4, 7, 2, 7, 9,
       9, 9, 1, 2, 9, 5, 3, 3, 4, 9, 4, 2, 8, 4, 7, 2, 1, 3, 1, 8, 1, 1,
       2, 7, 5, 6, 1, 8, 7, 3, 3, 5, 2, 6, 1, 7, 9, 8, 5, 2, 6, 4, 4, 2,
       9, 2, 6, 6, 1, 2, 8, 8, 9, 5, 3, 6, 6, 5, 3, 5, 7, 4, 7, 2, 9, 7,
       2, 6, 1, 3, 2, 4, 9, 5, 7, 2, 3, 4, 4, 8, 8, 2, 6, 6, 6, 3, 4, 1,
       1, 6, 9, 7, 7, 5, 6, 5, 5, 3, 9, 7, 8, 9, 4, 4, 4, 1, 2, 5, 1, 9,
       8, 4, 9, 4, 4, 8, 8, 8, 5, 7, 3, 2, 3, 1, 7, 7, 5, 4, 6, 5, 2, 6,
       4, 4, 2, 1, 6, 3, 8, 4, 8, 1, 5, 4, 6, 1, 2, 8, 1, 6, 1, 2, 9, 2,
       8, 5, 4, 4, 1, 5, 7, 7, 7, 9, 4, 6, 8, 1, 9, 2, 3, 4, 6, 2, 7, 2,
       1, 3, 1, 7, 8, 6, 7, 1, 5, 8, 1, 1, 8, 6, 1,

In [153]:
np.unique(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
np.unique(x, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([111, 117, 106, 114, 122, 101, 102, 133,  94]))

In [155]:
key, value = np.unique(x, return_counts=True)
print(key)
print(value)

[1 2 3 4 5 6 7 8 9]
[111 117 106 114 122 101 102 133  94]


In [156]:
list(zip(key, value))

[(1, 111),
 (2, 117),
 (3, 106),
 (4, 114),
 (5, 122),
 (6, 101),
 (7, 102),
 (8, 133),
 (9, 94)]

In [157]:
dict(zip(key, value))

{1: 111, 2: 117, 3: 106, 4: 114, 5: 122, 6: 101, 7: 102, 8: 133, 9: 94}

In [158]:
dict(zip(*np.unique(x,return_counts=True)))

{1: 111, 2: 117, 3: 106, 4: 114, 5: 122, 6: 101, 7: 102, 8: 133, 9: 94}

In [159]:
np.bincount(x, minlength=30)

array([  0, 111, 117, 106, 114, 122, 101, 102, 133,  94,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0])

In [160]:
np.arange(30), np.bincount(x, minlength=6)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([  0, 111, 117, 106, 114, 122, 101, 102, 133,  94]))