<a href="https://colab.research.google.com/github/KHB2937/DataAnalysis/blob/main/kwak/%EB%B3%B5%EC%8A%B5/ch05_01%2B02_%EB%B3%B5%EC%8A%B5_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## numpy

In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array((1, 2, 3))

array([1, 2, 3])

In [4]:
np.array(range(1,4))

array([1, 2, 3])

In [8]:
np.array([c for c in "1234"]) # 위의 코드와 똑같이 출력하려면 int(c) << np.array([int(c) for in "1234"])

array(['1', '2', '3', '4'], dtype='<U1')

In [11]:
arr = np.array([1, 2, 3])
type(arr)

numpy.ndarray

## 벡터화 연산

In [12]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
a + [10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
a * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
[v + 2 for v in a]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [20]:
[v * 2 for v in a]


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [21]:
arr = np.arange(10) # np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr + 2 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
(((arr * 5) // 2) - 1) % 7

array([6, 1, 4, 6, 2, 4, 0, 2, 5, 0])

In [24]:
arr == 5

array([False, False, False, False, False,  True, False, False, False,
       False])

In [25]:
arr[arr == 5]

array([5])

In [26]:
arr[arr > 5]

array([6, 7, 8, 9])

In [27]:
np.where(arr > 5)

(array([6, 7, 8, 9]),)

In [29]:
arr2 = np.arange(6, 25, 2)
arr2

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [31]:
np.where(arr % 3 == 0)

(array([0, 3, 6, 9]),)

In [32]:
arr2[np.where(arr2 % 3 == 0)]

array([ 6, 12, 18, 24])

In [33]:
arr2[[0] * 5]

array([6, 6, 6, 6, 6])

In [36]:
arr[(arr > 5) & (arr % 2 == 0)]

array([6, 8])

In [38]:
# ndarray
np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [40]:
np.array([[1, 2, 3, 4], [1, 2, 3]])

<ipython-input-40-e6426570ace6>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, 2, 3, 4], [1, 2, 3]])


array([list([1, 2, 3, 4]), list([1, 2, 3])], dtype=object)

In [42]:
a1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [44]:
a1.ndim, a1.shape

(2, (2, 4))

In [52]:
m = np.array([[1, 2], [3, 4]])
m2 = np.array((range(2,4), range(5, 7)))
print(m)
print(m2)

[[1 2]
 [3 4]]
[[2 3]
 [5 6]]


In [54]:
t = np.array([
    [
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]
    ],
    [
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]
    ]
])
t

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [55]:
t.ndim, t.shape

(3, (2, 3, 4))

In [56]:
a = np.arange(10).reshape(2, 4)

ValueError: ignored

In [58]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [59]:
b = a
b[0, 1] = 9

In [60]:
print(a)
print(b)

[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [62]:
c = a.copy()
c[2, 1] = -99
print(a)
print(c)

[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[  0   9]
 [  2   3]
 [  4 -99]
 [  6   7]
 [  8   9]]


## 인덱싱

In [64]:
a = np.arange(1, 100, 25)
a

array([ 1, 26, 51, 76])

In [65]:
a[2], a[-1], a[len(a)-1]# a[2], a[-1], a[a.shape[0]-1]

(51, 76, 76)

In [66]:
a[3], a[-1], a[a.shape[0]-1]

(76, 76, 76)

In [69]:
#,(comma)[][]
m = np.arange(6).reshape((2, 3))
m

array([[0, 1, 2],
       [3, 4, 5]])

In [73]:
m[0, 0], m[0,1]

(0, 1)

In [ ]:
m[m.shape[0]-2, 0], m[m.shape[0]-2, m.shape[1]-1]


In [76]:
m[-2, 0], m[-2, -1]

(0, 2)

In [78]:
d1, d2 = m.shape

In [79]:
m[d1-2, 0], m[d1-2, d2-1]

(0, 2)

## 슬라이싱

In [81]:
# :
a[1:2]

array([26])

In [84]:
a2 = np.arange(0, 100, 10)
a2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [86]:
a2[1:10:2], a2[10::-1],a2[::-1], a2[:]

(array([10, 30, 50, 70, 90]),
 array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0]),
 array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [87]:
m

array([[0, 1, 2],
       [3, 4, 5]])

In [88]:
m[0,:], m[0]

(array([0, 1, 2]), array([0, 1, 2]))

In [90]:
m[:, 0]
print(m[:, 0:1])

[[0]
 [3]]


## 배열의 자료형

In [93]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [94]:
x = np.array([1.0, 2.0, 3])
x.dtype

dtype('float64')

In [95]:
x = np.array([1, 0.2, 3])
x.dtype

dtype('float64')

In [96]:
x = np.array([1, 2.0, '3'])
x.dtype

dtype('<U32')

In [97]:
x = np.array([1, 2, 3], dtype='i')
x2 = np.array([1, 2, 3], dtype=int)
print(x, x.dtype)
print(x2, x2.dtype)

[1 2 3] int32
[1 2 3] int64


In [98]:
x = np.array([1, 2, 3.5], dtype='i')
print(x, x.dtype)

[1 2 3] int32


In [99]:
x = np.array([1, 2, "안농"], dtype='i')
print(x, x.dtype)

ValueError: ignored

In [101]:
a = np.zeros(5)
b = np.array([0, 1, 0, 1, 0])
a/b, b/a #int -> infinity

<ipython-input-101-085002b4f9f0>:3: RuntimeWarning: invalid value encountered in true_divide
  a/b, b/a #int -> infinity
<ipython-input-101-085002b4f9f0>:3: RuntimeWarning: divide by zero encountered in true_divide
  a/b, b/a #int -> infinity


(array([nan,  0., nan,  0., nan]), array([nan, inf, nan, inf, nan]))

In [102]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [103]:
np.ones(4)

array([1., 1., 1., 1.])

In [104]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [105]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [106]:
np.ones_like(a)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [107]:
np.empty((2, 5))

array([[2.71653339e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.84584433e-258],
       [3.27009881e-032, 1.77291095e+160, 7.79056799e-091,
        1.84752511e+184, 6.92224303e-310]])

In [108]:
np.linspace(10, 100, 5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [109]:
np.logspace(0.1, 1, 5)

array([ 1.25892541,  2.11348904,  3.54813389,  5.95662144, 10.        ])

In [111]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
A.ndim, A.shape

(2, (2, 3))

In [116]:
A2 = A.T
A2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [118]:
A2.ndim, A2.shape

(2, (3, 2))

In [120]:
A, A.flatten(), A.ravel()

(array([[1, 2, 3],
        [4, 5, 6]]), array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 4, 5, 6]))

In [121]:
t = np.arange(30).reshape(3, 5, 2)
t

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [123]:
t.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [125]:
x = np.arange(5)
print(x, x.ndim, x.shape)
x2 = x[:, np.newaxis]
print(x2, x2.ndim, x2.shape)
x3 = x[np.newaxis, :]
print(x3, x3.ndim, x3.shape)

[0 1 2 3 4] 1 (5,)
[[0]
 [1]
 [2]
 [3]
 [4]] 2 (5, 1)
[[0 1 2 3 4]] 2 (1, 5)
